USE CLARITY

SELECT req.[HLR_ID]
      ,req.[HLR_NAME]
      ,req.[HLR_TYPE_C] 
	  ,zht.NAME AS HLR_TYPE_NAME
	  ,reqst.LINE AS HL_REQ_STATUS_AUDIT_LINE
	  ,reqst.EVENT_LOCAL_DTTM
	  ,reqst.STATUS_C AS HL_REQ_STATUS
	  ,zhrs3.NAME AS HL_REQ_STATUS_NAME
	  ,reqst.CANCEL_RSN_C AS HL_REQ_STATUS_CANCEL_RSN
	  ,zhrcr2.NAME AS HL_REQ_STATUS_CANCEL_RSN_NAME
	  ,job.LINE AS JOB_ACTIONS_LINE
	  ,job.HL_ACTION_HL_REQ_STATUS_C
	  ,zhrs.NAME AS HL_ACTION_HL_REQ_STATUS_NAME
	  ,job.HL_ACTION_C
	  ,zha.NAME AS HL_ACTION_NAME
	  ,job.HL_ACTION_RESULT_C
	  ,zhar.NAME AS HL_ACTION_RESULT_NAME
	  --,grp.GROUP_STATUS_C
	  --,zhrs3.NAME AS GROUP_STATUS_NAME
	  --,grp.GROUP_TYPE_C
	  --,zhgt.NAME AS GROUP_TYPE_NAME
	  --,grp.GROUP_ASGN_TECH_ID
	  --,grp.GROUP_SHIFT_ID
	  --,grp.GROUP_REGION_SEC_ID
	  ,asgn.ASSIGNMENT_DATE_REAL,
       asgn.ASSIGNMENT_CSN_ID,
       asgn.ASGN_STATUS_C,
	   zhrs2.NAME AS ASGN_STATUS_NAME,
       asgn.ASGN_CANCEL_RSN_C,
	   zhrcr.NAME AS ASGN_CANCEL_RSN_NAME,
       asgn.ASGN_STATUS_SRC_C,
	   zhass.NAME AS ASGN_STATUS_SRC_C,
       asgn.ASGN_TECH_ID,
       asgn.ASGN_GROUP_HLR_ID,
       asgn.AUTO_ASSIGN_TOTAL_SCORE,
       asgn.AUTO_ASSIGN_TIME_SCORE,
       asgn.AUTO_ASSIGN_PROXIMITY_SCORE,
       asgn.AUTO_ASSIGN_PRIORITY_SCORE,
       asgn.AUTO_ASSIGN_ADDL_TECH_SCORE,
       asgn.AUTO_ASSIGN_LINKED_EVENT_SCORE,
       asgn.AUTO_ASSIGN_TASK_SCORE,
       asgn.AUTO_ASSIGN_LOCATION_SCORE,
       asgn.AUTO_ASSIGN_RULE_SCORE,
       asgn.AUTO_ASSIGN_PND_SCORE,
       asgn.AUTO_ASSIGN_SKILL_SCORE,
       asgn.AUTO_ASSIGN_MODE_SCORE
      ,[REQ_TEMPLATE_TASK_ID]
      ,[REQ_START_UTC_DTTM]
      ,[REQ_PRIORITY_C]
      ,[REQ_START_PLF_ID]
      ,[REQ_DYNAMIC_START_TYPE_C]
      ,[REQ_END_PLF_ID]
      ,[REQ_DYNAMIC_END_TYPE_C]
      ,[REQ_TECHS_NUM]
      ,[REQ_MODE_C]
      ,[REQ_STATUS_C]
      ,[REQ_CANCEL_RSN_C]
      ,[REQ_START_APPT_PAT_ENC_CSN_ID]
      ,[REQ_END_APPT_PAT_ENC_CSN_ID]
      ,[REQ_ADMISSION_PAT_ENC_CSN_ID]
      ,[REQ_PEND_ID]
      ,[REQ_EVENT_ID]
      ,[REQ_MULTI_STAGE_TEMPLT_TASK_ID]
      ,[REQ_FIRST_STAGE_HLR_ID]
      ,[REQ_NEXT_STAGE_HLR_ID]
      ,[REQ_STAGE_NUM]
      ,[REQ_IS_CONCURRENT_STAGE_YN]
      ,[REQ_REGION_SEC_ID]
      ,[REQ_SECTOR_SEC_ID]
      ,[REQ_DEPARTMENT_ID]
      ,[REQ_HOSP_LOC_ID]
      ,[REQ_SERV_AREA_ID]
      ,[REQ_CREATION_SOURCE_C]
      ,[REQ_CREATE_USER_ID]
      ,[REQ_CREATE_TECH_ID]
      ,[REQ_CREATE_DEPARTMENT_ID]
      ,[REQ_PHONE_NUMBER]
      ,[REQ_PAT_ID]
      ,[REQ_BED_TYPE_C]
      ,[REQ_FUNC_COMP_UTC_DTTM]
      ,[REQ_ACTIVATION_UTC_DTTM]
      ,[JOB_PARENT_REQ_ID]
      ,[REQ_START_LOCAL_DTTM]
      ,[REQ_FUNC_COMP_LOCAL_DTTM]
      ,[REQ_ACTIVATION_LOCAL_DTTM]
      ,[HL_FUNC_TYPE_C]
      ,[JOB_ACT_LINK_BED_CLEAN_HLR_ID]
      ,[JOB_ACT_LINK_LOCATION_EVNT_ID]
      ,[REQ_TASK_SUBTYPE_C]
      ,[REQ_BED_ID]
      ,[PREVIOUS_OUTGOING_EVENT_ID]
      ,[NEXT_INCOMING_EVENT_ID]
      ,[REQ_CANCEL_USER_ID]
      ,[REQ_INIT_ACTIVATION_UTC_DTTM]
      ,[REQ_INIT_ACTIVATION_LOCAL_DTTM]
      ,[FOLLOW_UP_SOURCE_HLR_ID]
      ,[JOB_VERIFICATION_METHOD_C]
      ,[JOB_BARCODE_OVERRIDE_REASON_C]
      ,[JOB_VERIFICATION_TECH_ID]
      ,[REQ_TRIP_TYPE_C]
      ,[JOB_RND_TRIP_LEG_C]
      ,[JOB_ACT_LINK_BEV_RECORD_ID]
      ,[BED_CLEAN_SOURCE_HLR_ID]
      ,[RECORD_STATUS_C]
      ,[REQ_CANCEL_BED_STATUS_C]
      ,[JOB_TTL_SECONDS_ESCALATED_NUM]
      ,[PRIMARY_LINKED_EVENT_C]
      ,[REQ_CLN_BED_REQUEST_PEND_ID]
  FROM [CLARITY].[dbo].[HL_REQ_INFO] req
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HLR_TYPE zht
  ON zht.HLR_TYPE_C = req.HLR_TYPE_C
  LEFT OUTER JOIN [CLARITY].[dbo].HL_REQ_STATUS_AUDIT reqst
  ON reqst.HLR_ID = req.HLR_ID
  AND req.HLR_TYPE_C = 1
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_REQ_CANCEL_RSN zhrcr2
  ON zhrcr2.HL_REQ_CANCEL_RSN_C = reqst.CANCEL_RSN_C
  LEFT OUTER JOIN [CLARITY].[dbo].HL_JOB_ACTIONS job
  ON job.HLR_ID = req.HLR_ID
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_ACTION zha
  ON zha.HL_ACTION_C = job.HL_ACTION_C
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_ACTION_RESULT zhar
  ON zhar.HL_ACTION_RESULT_C = job.HL_ACTION_RESULT_C
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_REQ_STATUS zhrs
  ON zhrs.HL_REQ_STATUS_C = job.HL_ACTION_HL_REQ_STATUS_C
  LEFT OUTER JOIN [CLARITY].[dbo].HL_ASGN_INFO asgn
  ON asgn.HLR_ID = job.HLR_ID
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_REQ_CANCEL_RSN zhrcr
  ON zhrcr.HL_REQ_CANCEL_RSN_C = asgn.ASGN_CANCEL_RSN_C
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_REQ_STATUS zhrs2
  ON zhrs2.HL_REQ_STATUS_C = asgn.ASGN_STATUS_C
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_ASGN_STATUS_SRC zhass
  ON zhass.HL_ASGN_STATUS_SRC_C = asgn.ASGN_STATUS_SRC_C
  --LEFT OUTER JOIN [CLARITY].[dbo].HL_GROUP_INFO grp
  --ON grp.HLR_ID = req.HLR_ID
  LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_REQ_STATUS zhrs3
  ON zhrs3.HL_REQ_STATUS_C = reqst.STATUS_C
  --LEFT OUTER JOIN [CLARITY].[dbo].ZC_HL_GROUP_TYPE zhgt
  --ON zhgt.HL_GROUP_TYPE_C = grp.GROUP_TYPE_C
  WHERE req.HLR_NAME = 'Bed Clean'
  AND ((req.HLR_TYPE_C = 1) OR (req.HLR_TYPE_C = 3 AND job.HL_ACTION_C <> 8))
  AND req.HLR_ID IN (85697,85698)
  --AND req.REQ_EVENT_ID = 32293793
  --ORDER BY req.HLR_TYPE_C, req.HLR_ID, JOB_ACTIONS_LINE, asgn.ASSIGNMENT_DATE_REAL
  --ORDER BY req.HLR_ID, req.HLR_TYPE_C,JOB_ACTIONS_LINE, asgn.ASSIGNMENT_DATE_REAL
  ORDER BY req.HLR_ID, req.HLR_TYPE_C,HL_REQ_STATUS_AUDIT_LINE, EVENT_LOCAL_DTTM, JOB_ACTIONS_LINE, asgn.ASSIGNMENT_DATE_REAL