USE [CLARITY_App_Dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Rptg].[UA_GPP_Department_Mapping](
	[DEPARTMENT_ID] [NUMERIC](18,0) NOT NULL,
	[DEPARTMENT_NAME] [VARCHAR](254) NULL,
	[ASCEND_VALUE] [VARCHAR](255) NULL
) ON [PRIMARY]
GO

GRANT DELETE, INSERT, SELECT, UPDATE ON [Rptg].[UA_GPP_Department_Mapping] TO [HSCDOM\Decision Support]
GO


