USE [CLARITY_App_Dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Rptg].[UA_GPP_Loc_to_Hosp](
	[LOC_ID] [INTEGER] NOT NULL,
	[LOC_NAME] [VARCHAR](100) NOT NULL,
	[ASCEND_VALUE] [VARCHAR](255) NULL
) ON [PRIMARY]
GO

GRANT DELETE, INSERT, SELECT, UPDATE ON [Rptg].[UA_GPP_Loc_to_Hosp] TO [HSCDOM\Decision Support]
GO


