USE [CLARITY_App_Dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Rptg].[UA_GPP_Guar_Rltn_to_Pt](
	[GUAR_REL_TO_PAT_C] [INTEGER] NOT NULL,
	[NAME] [VARCHAR](50) NOT NULL,
	[ABBR] [VARCHAR](50) NULL,
	[ASCEND_VALUE] [VARCHAR](255) NULL
) ON [PRIMARY]
GO

GRANT DELETE, INSERT, SELECT, UPDATE ON [Rptg].[UA_GPP_Guar_Rltn_to_Pt] TO [HSCDOM\Decision Support]
GO


