USE CLARITY

DECLARE @StartDate DATE
DECLARE @EndDate DATE
DECLARE @de_control VARCHAR(10)
DECLARE @WQ VARCHAR(18)

SET @StartDate = '1/1/2025'
SET @EndDate = '1/8/2025'
SET @de_control = 'UVA-MC'
SET @WQ = '2555' -- OP PRIMARY CARE POD MISSING REG ITEMS

;WITH MDM_REV_LOC_ID AS 
(	
	SELECT 
		DISTINCT 	
		t1.REV_LOC_ID
		,t1.HOSPITAL_CODE
		,t1.DE_HOSPITAL_CODE
		,t1.HOSPITAL_GROUP
	FROM	
		[CLARITY_App].[Rptg].[vwRef_MDM_Location_Master_Hospital_Group] t1
	WHERE	
		(t1.REV_LOC_ID IS NOT NULL)
)

SELECT 
			REGHX.REG_HX_AFF_WQ_ITEM_ID
			,REGHX.REG_HX_EVENT_C
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('71', '82','73') 
						THEN 1
						ELSE 0
						END																		'WQ CREATED'
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('77', '72','74') 
						THEN 1
						ELSE 0
						END																		'WQ RESOLVED'
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('71', '82','73') 
						THEN REGHX.REG_HX_USER_ID
						ELSE ''
						END																		'WQITM_CREATED_USER'
			
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('71', '82','73') 
						THEN CONCAT(CRTEMP.NAME, ' ','(', CRTEMP.SYSTEM_LOGIN,')')	
						ELSE ''
						END																		'WQITM_CREATED_USER_ID'
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('71', '82','73')
						THEN REGHX.REG_HX_LOGIN_DEP_ID	
						ELSE 0
						END																		'WQITM_CREATED_DEPT_ID'
	
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('71', '82','73')
						THEN CRTDEP.DEPARTMENT_NAME	
						ELSE ''
						END																		'WQITM_CREATED_DEPT'
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('71', '82','73')
						THEN EPIC_UTIL.EFN_UTC_TO_LOCAL(REGHX.REG_HX_INST_UTC_DTTM)
						ELSE NULL
						END																		'WQITM_CREATED_DTTM'
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('72', '77','74')
						THEN REGHX.REG_HX_USER_ID		
						ELSE ''
						END																		'WQITM_RESOLVED_USER'
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('72', '77','74')
						THEN CONCAT( RSVEMP.NAME , ' ','(',RSVEMP.SYSTEM_LOGIN,')'	)
						ELSE ''
						END																		'WQITM_RESOLVED_USER_ID'
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('72', '77','74') 
						THEN REGHX.REG_HX_LOGIN_DEP_ID	
						ELSE 0
						END																		'WQITM_RESOLVED_DEPT_ID'
	
			,CASE WHEN REGHX.REG_HX_EVENT_C IN ('72', '77','74')
						THEN CRTDEP.DEPARTMENT_NAME	
						ELSE ''
						END																		'WQITM_RESOLVED_DEPT'
	 	    ,CASE WHEN REGHX.REG_HX_EVENT_C IN ('72', '77','74')
						THEN EPIC_UTIL.EFN_UTC_TO_LOCAL(REGHX.REG_HX_INST_UTC_DTTM) 
						ELSE ''
						END																		'WQITM_RESOLVED_DTTM'
	
			,REGHX.REG_HX_OPEN_PAT_ID
			,REGHX.REG_HX_OPEN_PAT_CSN
			,WQ.[# CONTACTS]
			,WQ.[# USERS]
			,IDX.IDENTITY_ID				'MRN'
FROM 
		--WQ ITEM CREATE
		(SELECT *
		FROM CLARITY.dbo.REG_HX hx
		WHERE 1=1 
		AND HX.REG_HX_AFF_WQ_ID=@WQ
		AND HX.REG_HX_EVENT_C IN ('71','82', '72','77','73','74')  --Workqueue contact created /73 - Workqueue rules added / 82 - Workqueue contact returned from admin WQ
		AND CAST(EPIC_UTIL.EFN_UTC_TO_LOCAL(HX.REG_HX_INST_UTC_DTTM) AS DATE) >=@StartDate
		AND CAST(EPIC_UTIL.EFN_UTC_TO_LOCAL(HX.REG_HX_INST_UTC_DTTM) AS DATE) <=@EndDate
		) REGHX

		--WQ ITEM RESOLVED
/*LEFT OUTER JOIN (
					SELECT *
					FROM CLARITY.dbo.REG_HX hx
					WHERE 1=1 
		--			AND hx.REG_HX_AFF_WQ_ITEM_ID='102570992'
					AND HX.REG_HX_AFF_WQ_ID=@WQ
		--			AND HX.REG_HX_EVENT_C IN ('72','77')  -- Workqueue contact resolved
					AND CAST(EPIC_UTIL.EFN_UTC_TO_LOCAL(HX.REG_HX_INST_UTC_DTTM) AS DATE) >=@StartDate
					AND CAST(EPIC_UTIL.EFN_UTC_TO_LOCAL(HX.REG_HX_INST_UTC_DTTM) AS DATE) <=@EndDate
				) RSVHX													ON CRTHX.REG_HX_EVENT_ID=	RSVHX.REG_HX_WQ_PAIRED_EVENT_ID			---RSVHX.REG_HX_WQ_PAIRED_EVENT_ID
 */
		--ACTIVITY IN WQ
 LEFT OUTER JOIN (
					SELECT HX.REG_HX_AFF_WQ_ITEM_ID		'WQ_ITM_ID'
							,COUNT(DISTINCT HX.REG_HX_USER_ID) '# USERS'
							,COUNT(HX.REG_HX_EVENT_ID) '# CONTACTS'
					FROM CLARITY.dbo.REG_HX hx
					WHERE HX. REG_HX_AFF_WQ_ID=@WQ
							AND HX.REG_HX_EVENT_C IN ('71','82', '72','77','73','74')
							AND CAST(EPIC_UTIL.EFN_UTC_TO_LOCAL(HX.REG_HX_INST_UTC_DTTM) AS DATE) >=@StartDate
							AND CAST(EPIC_UTIL.EFN_UTC_TO_LOCAL(HX.REG_HX_INST_UTC_DTTM) AS DATE) <=@EndDate
							
					GROUP BY HX.REG_HX_AFF_WQ_ITEM_ID
				  ) WQ												ON REGHX.REG_HX_AFF_WQ_ITEM_ID=WQ.WQ_ITM_ID
 
 
		--REFERENCE
LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP CRTEMP							ON REGHX.REG_HX_USER_ID=CRTEMP.USER_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP RSVEMP							ON REGHX.REG_HX_USER_ID=RSVEMP.USER_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_DEP CRTDEP							ON REGHX.REG_HX_LOGIN_DEP_ID=CRTDEP.DEPARTMENT_ID
LEFT OUTER JOIN MDM_REV_LOC_ID mloc			                            ON mloc.REV_LOC_ID = CRTDEP.REV_LOC_ID		--Location Update
--LEFT OUTER JOIN CLARITY.dbo.CLARITY_DEP RSVDEP							ON HX.REG_HX_LOGIN_DEP_ID=RSVDEP.DEPARTMENT_ID
LEFT OUTER JOIN CLARITY.dbo.REG_HX_AFF_PAT_RECS REGPT					ON REGHX.REG_HX_EVENT_ID=REGPT.REG_HX_EVENT_ID 
LEFT OUTER JOIN (SELECT *
					FROM CLARITY.dbo.IDENTITY_ID
					WHERE IDENTITY_TYPE_ID='14') IDX								ON REGPT.REG_HX_AFF_PAT_ID=IDX.PAT_ID



WHERE 1=1
	AND
    (
    (UPPER(@de_control)=coalesce(UPPER(mloc.de_hospital_code),'UVA-MC'))
    OR (UPPER(@de_control)=coalesce(UPPER(mloc.hospital_group),'UVA-MC'))
    OR (UPPER(@de_control)='ALL')
    )