USE [CLARITY_App_Dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Stage].[AmbOptHuddle_Dash_Unavail_Rsn_Slot_Utilization](
	[event_type] [VARCHAR](50) NULL,
	[event_count] [INT] NOT NULL,
	[event_date] [SMALLDATETIME] NOT NULL,
	[fmonth_num] [SMALLINT] NOT NULL,
	[Fyear_num] [SMALLINT] NOT NULL,
	[FYear_name] [VARCHAR](10) NOT NULL,
	[report_period] [VARCHAR](10) NULL,
	[report_date] [SMALLDATETIME] NULL,
	[event_category] [VARCHAR](150) NULL,
	[pod_name] [VARCHAR](100) NULL,
	[hub_id] [VARCHAR](66) NULL,
	[hub_name] [VARCHAR](100) NULL,
	[epic_department_id] [NUMERIC](18, 0) NOT NULL,
	[epic_department_name] [VARCHAR](254) NULL,
	[epic_department_name_external] [VARCHAR](254) NULL,
	[provider_id] [VARCHAR](18) NOT NULL,
	[provider_name] [VARCHAR](200) NULL,
	[service_line_id] [SMALLINT] NULL,
	[service_line] [VARCHAR](150) NULL,
	[prov_service_line_id] [SMALLINT] NULL,
	[prov_service_line] [VARCHAR](150) NULL,
	[sub_service_line_id] [SMALLINT] NULL,
	[sub_service_line] [VARCHAR](150) NULL,
	[opnl_service_id] [SMALLINT] NULL,
	[opnl_service_name] [VARCHAR](150) NULL,
	[corp_service_line_id] [SMALLINT] NULL,
	[corp_service_line] [VARCHAR](150) NULL,
	[hs_area_id] [SMALLINT] NULL,
	[hs_area_name] [VARCHAR](150) NULL,
	[prov_hs_area_id] [SMALLINT] NULL,
	[prov_hs_area_name] [VARCHAR](150) NULL,
	[Regular_Openings] [INT] NULL,
	[Overbook_Openings] [INT] NULL,
	[Openings_Booked] [INT] NULL,
	[Regular_Openings_Available] [INT] NULL,
	[Regular_Openings_Unavailable] [INT] NULL,
	[Overbook_Openings_Available] [INT] NULL,
	[Overbook_Openings_Unavailable] [INT] NULL,
	[Regular_Openings_Booked] [INT] NULL,
	[Overbook_Openings_Booked] [INT] NULL,
	[Regular_Outside_Template_Booked] [INT] NULL,
	[Overbook_Outside_Template_Booked] [INT] NULL,
	[Regular_Openings_Available_Booked] [INT] NULL,
	[Overbook_Openings_Available_Booked] [INT] NULL,
	[Regular_Openings_Unavailable_Booked] [INT] NULL,
	[Overbook_Openings_Unavailable_Booked] [INT] NULL,
	[Regular_Outside_Template_Available_Booked] [INT] NULL,
	[Overbook_Outside_Template_Available_Booked] [INT] NULL,
	[Regular_Outside_Template_Unavailable_Booked] [INT] NULL,
	[Overbook_Outside_Template_Unavailable_Booked] [INT] NULL,
	[STAFF_RESOURCE_C] [INT] NULL,
	[STAFF_RESOURCE] [VARCHAR](20) NULL,
	[PROVIDER_TYPE_C] [VARCHAR](66) NULL,
	[PROV_TYPE] [VARCHAR](66) NULL,
	[financial_division_id] [INT] NULL,
	[financial_division_name] [VARCHAR](150) NULL,
	[financial_sub_division_id] [INT] NULL,
	[financial_sub_division_name] [VARCHAR](150) NULL,
	[rev_location_id] [INT] NULL,
	[rev_location] [VARCHAR](150) NULL,
	[som_group_id] [INT] NULL,
	[som_group_name] [VARCHAR](150) NULL,
	[som_department_id] [INT] NULL,
	[som_department_name] [VARCHAR](150) NULL,
	[som_division_id] [INT] NULL,
	[som_division_name] [VARCHAR](150) NULL,
	[BUSINESS_UNIT] [VARCHAR](20) NULL,
	[som_hs_area_id] [INT] NULL,
	[som_hs_area_name] [VARCHAR](150) NULL,
	[SUBLOC_ID] [VARCHAR](25) NULL,
	[SUBLOC_NAME] [VARCHAR](254) NULL,
	[app_flag] [INT] NULL,
	[UNAVAILABLE_RSN_C] [INT] NULL,
	[UNAVAILABLE_RSN_NAME] [VARCHAR](254) NULL,
	[AMB_Scorecard_Flag] [INT] NULL,
	[organization_id] [INT] NULL,
	[organization_name] [VARCHAR](50) NULL,
	[service_id] [INT] NULL,
	[service_name] [VARCHAR](150) NULL,
	[clinical_area_id] [INT] NULL,
	[clinical_area_name] [VARCHAR](150) NULL,
	[ambulatory_flag] [INT] NULL,
	[community_health_flag] [INT] NULL,
	[SnapShot_Dt] [DATETIME] NULL
) ON [PRIMARY]
GO


