USE [CLARITY_App_Dev]
GO

--DELETE FROM [Stage].[AmbOptHuddle_Dash_Unavail_Rsn_Slot_Utilization]
--      WHERE CAST(SnapShot_Dt AS DATE) = '11/16/2025'
--GO

SELECT [event_type]
      ,[event_count]
      ,[event_date]
      ,[fmonth_num]
      ,[Fyear_num]
      ,[FYear_name]
      ,[report_period]
      ,[report_date]
      ,[event_category]
      ,[pod_name]
      ,[hub_id]
      ,[hub_name]
      ,[epic_department_id]
      ,[epic_department_name]
      ,[epic_department_name_external]
      ,[provider_id]
      ,[provider_name]
      ,[service_line_id]
      ,[service_line]
      ,[prov_service_line_id]
      ,[prov_service_line]
      ,[sub_service_line_id]
      ,[sub_service_line]
      ,[opnl_service_id]
      ,[opnl_service_name]
      ,[corp_service_line_id]
      ,[corp_service_line]
      ,[hs_area_id]
      ,[hs_area_name]
      ,[prov_hs_area_id]
      ,[prov_hs_area_name]
      ,[Regular_Openings]
      ,[Overbook_Openings]
      ,[Openings_Booked]
      ,[Regular_Openings_Available]
      ,[Regular_Openings_Unavailable]
      ,[Overbook_Openings_Available]
      ,[Overbook_Openings_Unavailable]
      ,[Regular_Openings_Booked]
      ,[Overbook_Openings_Booked]
      ,[Regular_Outside_Template_Booked]
      ,[Overbook_Outside_Template_Booked]
      ,[Regular_Openings_Available_Booked]
      ,[Overbook_Openings_Available_Booked]
      ,[Regular_Openings_Unavailable_Booked]
      ,[Overbook_Openings_Unavailable_Booked]
      ,[Regular_Outside_Template_Available_Booked]
      ,[Overbook_Outside_Template_Available_Booked]
      ,[Regular_Outside_Template_Unavailable_Booked]
      ,[Overbook_Outside_Template_Unavailable_Booked]
      ,[STAFF_RESOURCE_C]
      ,[STAFF_RESOURCE]
      ,[PROVIDER_TYPE_C]
      ,[PROV_TYPE]
      ,[financial_division_id]
      ,[financial_division_name]
      ,[financial_sub_division_id]
      ,[financial_sub_division_name]
      ,[rev_location_id]
      ,[rev_location]
      ,[som_group_id]
      ,[som_group_name]
      ,[som_department_id]
      ,[som_department_name]
      ,[som_division_id]
      ,[som_division_name]
      ,[BUSINESS_UNIT]
      ,[som_hs_area_id]
      ,[som_hs_area_name]
      ,[SUBLOC_ID]
      ,[SUBLOC_NAME]
      ,[app_flag]
      ,[UNAVAILABLE_RSN_C]
      ,[UNAVAILABLE_RSN_NAME]
      ,[AMB_Scorecard_Flag]
      ,[organization_id]
      ,[organization_name]
      ,[service_id]
      ,[service_name]
      ,[clinical_area_id]
      ,[clinical_area_name]
      ,[ambulatory_flag]
      ,[community_health_flag]
      ,[SnapShot_Dt]
  FROM [CLARITY_App_Dev].[Stage].[AmbOptHuddle_Dash_Unavail_Rsn_Slot_Utilization]
  ORDER BY
	event_category,
	event_date

GO


