USE [CLARITY_App]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--EXEC [Rptg].[uspSrc_ADT_Txport_DelayReasons] '12/01/2010','12/31/2017'

--ALTER PROCEDURE [Rptg].[uspSrc_ADT_Txport_DelayReasons] 
-- =============================================
/*******************************************************************************************
WHAT:	 Delayed trasnport events
WHO :	 Transport -Sherrie Whyte
WHEN:	 Ad Hoc 
WHY :	 SSRS Report
AUTHOR:	 Brian Costello/Mali A.
			
SPEC:	
		All delayed transport events
--------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------
MODS: 
	05/10/18 - Initial draft created
		
*******************************************************************************************/

	-- Add the parameters for the stored procedure here
--	(
--	@StartDate DATETIME,
--	@EndDate DATETIME

--	)
--AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;




DECLARE @startDate DATETIME ='1/1/2023';
DECLARE @EndDate DATETIME ='1/9/2023';

SELECT 
TXPORT_EVENTS.TXPORT_ID
,TXPORT_EVENTS.LINE
,TXPORT_EVENTS.ASGN_STATUS_C
,ZC_ASGN_STATUS.NAME  ASGN_STATUS
,TXPORT_EVENTS.EVENT_INSTANT_DTTM
,TXPORT_EVENTS.WORKER_ID   ASSIGNED_TRANSPORTER_ID
,CL_HKR.RECORD_NAME  ASSIGNED_TRANSPORTER_NAME
,TXPORT_EVENTS.TXPORT_DLY_RSN_C
,ZC_TXPORT_DLY_RSN.NAME   DELAY_REASON
,TXPORT_EVENTS.TXPORT_CANC_RSN_C
,ZC_TXPORT_CANC_RSN.NAME    CANCEL_REASON
,TXPORT_EVENTS.HKR_TXPORT_ID   TRANSPORTER_ID_WHO_CHANGE_REQ_STATUS
,CL_HKR_CHG.RECORD_NAME  TRANSPORTER_NAME_WHO_CHANGED_REQ_STATUS
,TXPORT_EVENTS.EMP_TXPORT_ID     USER_ID_WHO_CHANGE_REQ_STATUS 
,CLARITY_EMP.NAME  USER_NAME_WHO_CHANGE_REQ_STATUS 
,TXPORT_EVENTS.EVENT_INSTANT_LOCAL_DTTM

FROM CLARITY.dbo.TXPORT_EVENTS
LEFT JOIN CLARITY.dbo.CL_HKR ON TXPORT_EVENTS.WORKER_ID=CL_HKR.RECORD_ID
LEFT JOIN CLARITY.dbo.CL_HKR CL_HKR_CHG ON TXPORT_EVENTS.WORKER_ID=CL_HKR_CHG.RECORD_ID
LEFT JOIN CLARITY.dbo.CLARITY_EMP ON TXPORT_EVENTS.EMP_TXPORT_ID=CLARITY_EMP.USER_ID
LEFT JOIN CLARITY.dbo.ZC_TXPORT_DLY_RSN  ON ZC_TXPORT_DLY_RSN.TXPORT_DLY_RSN_C=TXPORT_EVENTS.TXPORT_DLY_RSN_C
LEFT JOIN CLARITY.dbo.ZC_TXPORT_CANC_RSN  ON ZC_TXPORT_CANC_RSN.TXPORT_CANC_RSN_C=TXPORT_EVENTS.TXPORT_CANC_RSN_C
LEFT JOIN CLARITY.dbo.ZC_ASGN_STATUS  ON  ZC_ASGN_STATUS.ASGN_STATUS_C=TXPORT_EVENTS.ASGN_STATUS_C

WHERE 1=1
		AND CLARITY.dbo.TXPORT_EVENTS.ASGN_STATUS_C='4'
		AND CLARITY.dbo.TXPORT_EVENTS.EVENT_INSTANT_DTTM>=@StartDate
		AND CLARITY.dbo.TXPORT_EVENTS.EVENT_INSTANT_DTTM<=@EndDate

ORDER BY
	TXPORT_ID,
	LINE

END 
	
GO


