USE CLARITY

SELECT
	pt.PAT_ID,
	pt.PAT_ENC_CSN_ID,
	pt.CARE_TEAMS_ID,
	pt.RECORD_NAME
FROM
(
SELECT DISTINCT
       ect.PAT_ID,
	   ect.PAT_ENC_CSN_ID,
	   ect.LINE,
	   ect.CARE_TEAMS_ID,
	   pri.RECORD_NAME,
	   eta.PRIMARYTEAM_AUDI_YN,
	   eta.TEAM_AUDIT_INSTANT,
	   ROW_NUMBER() OVER(PARTITION BY ect.PAT_ID, ect.PAT_ENC_CSN_ID ORDER BY eta.TEAM_AUDIT_INSTANT DESC) AS seq

FROM CLARITY.dbo.EPT_CARE_TEAMS ect

LEFT OUTER JOIN CLARITY.dbo.PROVTEAM_REC_INFO pri
  ON ect.CARE_TEAMS_ID = pri.ID

LEFT OUTER JOIN CLARITY.dbo.EPT_TEAM_AUDIT eta
	ON eta.PAT_ID = ect.PAT_ID
	AND eta.PAT_ENC_CSN_ID = ect.PAT_ENC_CSN_ID
	AND eta.TEAM_AUDIT_ID = ect.CARE_TEAMS_ID
  --WHERE RECORD_NAME LIKE '%BLUE%'
  ) pt
  WHERE pt.seq = 1

--ORDER BY CARE_TEAMS_ID
--ORDER BY RECORD_NAME
--ORDER BY
--       ect.PAT_ID,
--	   ect.PAT_ENC_CSN_ID,
--	   ect.LINE
ORDER BY
       pt.PAT_ID,
	   pt.PAT_ENC_CSN_ID