USE CLARITY

DROP TABLE IF EXISTS #item_index
DROP TABLE IF EXISTS #mgr_emp_map

--DECLARE @p_DateStart	DATETIME	=	'2023-07-01'
--DECLARE @p_DateEnd	DATETIME	=	'2024-03-31'
;

WITH item_index	AS 
	(	SELECT	ITEM_ID
		FROM	PAT_WQ_ITEMS			
		WHERE	WORKQUEUE_ID = '2555'			--OP Primary Care Pod Missing Reg Items
			AND ENTRY_DATE		BETWEEN @p_DateStart	AND @p_DateEnd

			UNION

		SELECT	ITEM_ID
		FROM	PAT_WQ_ITEMS		pawi					
		WHERE	WORKQUEUE_ID = '2555'
			AND RELEASE_DATE	BETWEEN @p_DateStart	AND @p_DateEnd
	)

SELECT * INTO #item_index FROM item_index
CREATE CLUSTERED INDEX  items ON #item_index (ITEM_ID)
;

WITH mgr_emp AS (
	SELECT	crpt.REPORT_NAME 'TEMPLATE_DISP_NM', tein.REPORT_ID, tein.REPORT_NAME 'TEMPLATE_NAME', rein.REPORT_INFO_NAME, rein.REPORT_INFO_ID
		,	seet.EXPRSN_VALUE	'PRACTICE'
		,	emps.NAME 'SUPV_NAME',	emps.SYSTEM_LOGIN 'SUPV_LOGIN', emps.USER_ID 'SUPV_ID'	
		,	empe.NAME 'EMP_NAME',	empe.SYSTEM_LOGIN 'EMP_LOGIN',	empe.USER_ID 'EMP_ID'
			--,	rein.TEMP_REPORT_C,	REPORT_INFO_NAME
	
	--INTO	#mgr_emp_map_temp
	FROM	REPORT_INFO	rein
				INNER JOIN	TEMPLATE_INFO		tein	ON rein.REPORT_ID = tein.REPORT_ID			--HGR
				LEFT JOIN	CLARITY_RPT			crpt	ON tein.REPORT_ID = crpt.ASSOC_REPORT_ID	--RPT
				INNER JOIN	SEARCH_EXPRESSION	seex	ON rein.REPORT_INFO_ID = seex.REPORT_INFO_ID	AND seex.PARAMETER_UNIQ = 100012			--Report ID
				LEFT JOIN	SEARCH_EXPRESSION	seet	ON rein.REPORT_INFO_ID = seet.REPORT_INFO_ID	AND seet.PARAMETER_UNIQ = 100009			--Text label
				LEFT JOIN	SEARCH_EXPRESSION	sees	ON rein.REPORT_INFO_ID = sees.REPORT_INFO_ID	AND sees.PARAMETER_UNIQ = 100010			--Supervisor
				LEFT JOIN	SEARCH_EXPRESSION	seee	ON rein.REPORT_INFO_ID = seee.REPORT_INFO_ID	AND seee.PARAMETER_UNIQ = 100011			--Employees
	
				LEFT JOIN	CLARITY_EMP			emps	ON sees.EXPRSN_VALUE = emps.USER_ID			--Supervisor
				LEFT JOIN	CLARITY_EMP			empe	ON seee.EXPRSN_VALUE = empe.USER_ID			--Employees
				
	WHERE	1=1
		AND rein.REPORT_ID = 100791	
		AND rein.TEMP_REPORT_C <> 1					--1=Unsaved Report		
		AND seex.EXPRSN_VALUE = '45426'
		AND sees.EXPRSN_VALUE <> seee.EXPRSN_VALUE	--Exclude Supervisors mapped to themselves here, add them back later
	)

--Add dummy row for Supervisor as USER
SELECT	*
INTO	#mgr_emp_map 
FROM	(	SELECT DISTINCT PRACTICE, SUPV_NAME, SUPV_LOGIN, SUPV_ID, EMP_NAME, EMP_LOGIN, EMP_ID
			FROM	mgr_emp
			
			UNION ALL

			SELECT DISTINCT 'ALL' 'PRACTICE', SUPV_NAME, SUPV_LOGIN, SUPV_ID
				,	SUPV_NAME 'EMP_NAME', SUPV_LOGIN 'EMP_LOGIN', SUPV_ID 'EMP_ID'
			FROM	mgr_emp
		)	mgr_emp_map
;

WITH detail AS (
SELECT	pawi.WORKQUEUE_ID, pawi.ITEM_ID
	,	pawi.PAT_ENC_CSN_ID	
	,	CASE WHEN pawi.RELEASE_DATE IS NULL THEN 'ACTIVE' WHEN pawi.RELEASE_DATE IS NOT NULL THEN 'RELEASED' ELSE 'OTHER' END 'ITEM_STATUS'
	,	pawi.ENTRY_DATE, dadi.YEAR_MONTH_STR			'MONTH_ENTRY'
	,	pawi.RELEASE_DATE, dadx.YEAR_MONTH_STR			'MONTH_EXIT'
	,	DATEDIFF(MINUTE,wquh.START_TIME,COALESCE(wqux.START_TIME,CAST(GETDATE() AS DATE)))	'MINS_IN_WQ'
	,	wquh.USER_ID 'USER_ID_ENTRY'
	,	wqux.USER_ID 'USER_ID_EXIT'
	,	CASE WHEN wquh.USER_ID = wqux.USER_ID THEN 'SELF' ELSE 'OTHER' END	'USER_MATCH_YN'

	,	wquh.ACTIVITY_DATA	'RULES_ENTRY_LIST'
	,	LEN(wquh.ACTIVITY_DATA) - LEN(REPLACE(wquh.ACTIVITY_DATA,'^','')) 'RULES_ENTRY'
	
	,	wqxr.ACTIVITY_DATA	'RULES_EXIT_LIST'
	,	LEN(wqxr.ACTIVITY_DATA) - LEN(REPLACE(wqxr.ACTIVITY_DATA,'^','')) 'RULES_EXIT'

	,	pawr.RULE_ID, ccer.RULE_NAME, 1 'RULE_COUNT'
	,	ROW_NUMBER() OVER (PARTITION BY pawi.ITEM_ID ORDER BY pawr.LINE) 'RN'

FROM PAT_WQ_ITEMS		pawi			
		INNER JOIN	#item_index			itin	ON pawi.ITEM_ID = itin.ITEM_ID
		LEFT JOIN	DATE_DIMENSION		dadi	ON pawi.ENTRY_DATE = dadi.CALENDAR_DT
		LEFT JOIN	DATE_DIMENSION		dadx	ON pawi.RELEASE_DATE = dadx.CALENDAR_DT
		LEFT JOIN	WQ_USR_HISTORY		wquh	ON itin.ITEM_ID = wquh.WQ_ITM_ID		AND wquh.WQ_ACTIVITY_C = 1		--1=ENTRY
		LEFT JOIN	WQ_USR_HISTORY		wqux	ON itin.ITEM_ID = wqux.WQ_ITM_ID		AND wqux.WQ_ACTIVITY_C IN (3,9) --3=Release, 9=Manually removed		
		LEFT JOIN	WQ_USR_HISTORY		wqxr	ON itin.ITEM_ID = wqxr.WQ_ITM_ID		AND wqux.LINE - 1 = wqxr.LINE	--Get prev line for rule count
		
		LEFT JOIN	PAT_WQI_RULES		pawr	ON pawi.ITEM_ID = pawr.ITEM_ID			AND wquh.LINE = pawr.LINE
		LEFT JOIN	CL_CHRG_EDIT_RULE	ccer	ON pawr.RULE_ID = ccer.RULE_ID
)

SELECT 
		SUM(SELF_RESOLVED)								'SELF_RESOLVED'
	,	SUM(COUNT_ENTRY)								'COUNT_ENTRY'
	,	100.0 * SUM(SELF_RESOLVED) / SUM(COUNT_ENTRY)	'SELF_RESOLVED_%'
	,	SUM(SELF_CAUSED)								'SELF_CAUSED'
	,	SUM(COUNT_EXIT)									'COUNT_EXIT'
	,	100.0 * SUM(SELF_CAUSED) / SUM(COUNT_EXIT)		'SELF_CAUSED_%'
	,	SUPV_NAME										'RPT_SUPV_NAME'
	,	SUPV_LOGIN										'RPT_SUPV_LOGIN'
	,	SUPV_ID											'RPT_SUPV_ID'
	,	PRACTICE										'RPT_PRACTICE'
	,	EMP_NAME										'RPT_EMP_NAME'
	,	EMP_LOGIN										'RPT_EMP_LOGIN'
	,	RPT_EMP_ID
	,	RPT_MONTH	
	,	RULE_NAME
FROM (
		SELECT	SUM(RULE_COUNT)					'COUNT_ENTRY'
				--SUM(RULES_ENTRY)				'COUNT_ENTRY'
			,	SUM(CASE WHEN USER_MATCH_YN = 'SELF' THEN RULE_COUNT ELSE 0 END)	'SELF_RESOLVED'
			,	NULL							'COUNT_EXIT'
			,	NULL							'SELF_CAUSED'
			,	USER_ID_ENTRY					'RPT_EMP_ID'
			,	MONTH_ENTRY						'RPT_MONTH'
			,	RULE_NAME						'RULE_NAME'
		FROM	detail
		WHERE	ENTRY_DATE BETWEEN @p_DateStart AND @p_DateEnd

		GROUP BY USER_ID_ENTRY,	MONTH_ENTRY,	RULE_NAME
		
			UNION ALL
		
		SELECT	NULL							'COUNT_ENTRY'
			,	NULL							'SELF_RESOLVED'
			,	SUM(RULES_EXIT)					'COUNT_EXIT'
			,	SUM(CASE WHEN USER_MATCH_YN = 'SELF' THEN RULES_EXIT ELSE 0 END)	'SELF_CAUSED'			
			,	USER_ID_EXIT					'RPT_EMP_ID'
			,	MONTH_EXIT						'RPT_MONTH'
			,	NULL							'RULE_NAME'
		FROM	detail
		WHERE	RELEASE_DATE BETWEEN @p_DateStart AND @p_DateEnd
			AND RN = 1
		GROUP BY USER_ID_EXIT,	MONTH_EXIT
		)	all_items
				INNER JOIN	#mgr_emp_map		mgem	ON all_items.RPT_EMP_ID = mgem.EMP_ID
GROUP BY 
	SUPV_NAME
,	SUPV_LOGIN
,	SUPV_ID
,	PRACTICE
,	EMP_NAME
,	EMP_LOGIN
,	RPT_EMP_ID
,	RPT_MONTH
,	RULE_NAME

ORDER BY RPT_SUPV_NAME, RPT_PRACTICE, RPT_EMP_NAME, RPT_MONTH