USE CLARITY
	SET NOCOUNT ON;

------FOR TESTING ONLY------
DECLARE  
	@StartDate DATETIME = '1/12/2025',
	@EndDate DATETIME = '2/12/2025',
	@de_control VARCHAR(255) = 'All';

	DECLARE @LookBackDays INTEGER
	SET @LookBackDays = 3

DROP TABLE IF EXISTS #MDM_REV_LOC_ID  
	SELECT 
		DISTINCT 	
		t1.REV_LOC_ID
		,t1.HOSPITAL_CODE
		,t1.DE_HOSPITAL_CODE
		,t1.HOSPITAL_GROUP
	INTO #MDM_REV_LOC_ID
	FROM	
		[CLARITY_App].[Rptg].[vwRef_MDM_Location_Master_Hospital_Group] t1
	WHERE	
		(t1.REV_LOC_ID IS NOT NULL)


--DROP TABLE IF EXISTS #cov;
--SELECT op.ORDER_PROC_ID, op.FUTURE_OR_STAND, e.PAT_ENC_CSN_ID, p.PAT_MRN_ID, p.PAT_ID,r.COMPONENT_ID, cc.COMMON_NAME AS RESULT_COMPONENT, r.ORD_VALUE, op.ORDERING_DATE, r.RESULT_TIME
----,ROW_NUMBER() OVER(PARTITION BY p.PAT_ID ORDER BY op.ORDERING_DATE DESC, op.FUTURE_OR_STAND ASC) rn   --choose resulted orders before standing or future
--INTO #cov
--FROM CLARITY.dbo.TEST_MSTR_DB_MAIN t
--INNER JOIN CLARITY.dbo.CLARITY_EAP eap on t.TEST_ID = eap.TEST_ID
--INNER JOIN CLARITY.dbo.ORDER_PROC op ON eap.PROC_ID = op.PROC_ID
--INNER JOIN CLARITY.dbo.PAT_ENC e ON op.PAT_ENC_CSN_ID = e.PAT_ENC_CSN_ID	
--LEFT JOIN CLARITY.dbo.PATIENT p ON e.PAT_ID = p.PAT_ID
--LEFT JOIN CLARITY.dbo.ORDER_RESULTS r ON op.ORDER_PROC_ID = r.ORDER_PROC_ID
--LEFT JOIN CLARITY.dbo.CLARITY_COMPONENT cc ON r.COMPONENT_ID = cc.COMPONENT_ID 
--WHERE  t.TEST_ID IN (
--'1230100751',	--COVID-19 (SARS-CoV-2) PCR, lower respiratory
--'1230100750'	--COVID-19  (SARS-CoV-2) PCR, upper respiratory
--)
--AND ISNULL(op.ORDER_STATUS_C, '') <> '4' --not canceled

--CREATE NONCLUSTERED INDEX ix_cov ON #cov (PAT_ID, ORDERING_DATE);

SELECT DISTINCT
       pat.PAT_MRN_ID,
	   pat.BIRTH_DATE,
	   SURGERY_DT_AGE = FLOOR((CAST (oc.SURGERY_DATE AS INTEGER) - CAST(pat.BIRTH_DATE AS INTEGER)) / 365.25),
       oc.OR_CASE_ID,
       COALESCE(a.OR_LINK_CSN, a.PAT_ENC_CSN_ID) OR_CSN_ID,
       zos.NAME SCHEDULE_STATUS,
       oloc.LOC_ID,
       loc.LOC_NAME,
	   ocat.HIST_SCHED_DTTM CASE_SCHEDULED_TIME,
       oc.SURGERY_DATE SCHEDULED_SURGERY_DATE,
	   oc.CASE_BEGIN_INSTANT,
	   oc.CASE_END_INSTANT,
       op.OR_PROC_ID,
       op.PROC_NAME PROCEDURE_NAME,
       ocap.LINE PROCEDURE_LINE,
       ocap.PANEL PROCEDURE_PANEL,
       surg_ser.PROV_ID SURGEON_ID,
       surg_ser.PROV_NAME SURGEON_NAME,
       --surg.LINE SURGEON_LINE,
       --surg.PANEL SURGEON_PANEL,
       --prov_dep.DEPARTMENT_NAME AS PROVIDER_DEPARTMENT,
    --   emp.USER_ID CREATED_USER_ID,
    --   emp.NAME CREATED_USER_NAME,
	   --sched_usr.USER_ID SCHEDULED_USER_ID,
	   --sched_usr.NAME SCHEDULED_USER_NAME,
       ocap.TOTAL_LENGTH
	   ----, covid.RESULT_COMPONENT COVID_TEST
	   ----,CASE WHEN  covid.ORD_VALUE IS NULL AND covid.ORDERING_DATE IS NOT NULL THEN 'Test Ordered' ELSE covid.ORD_VALUE END COVID_RESULT
	   --,COVID_RESULT = (SELECT TOP 1 ORD_VALUE FROM #cov c WHERE C.PAT_ID = pat.PAT_ID AND c.ORDERING_DATE <= oc.SURGERY_DATE ORDER BY c.ORDERING_DATE DESC, c.FUTURE_OR_STAND ASC) ---choose resulted orders before standing or future
	   --,COVID_ORDERING_DATE = (SELECT TOP 1 ORDERING_DATE FROM #cov c WHERE C.PAT_ID = pat.PAT_ID AND c.ORDERING_DATE <= oc.SURGERY_DATE ORDER BY c.ORDERING_DATE DESC, c.FUTURE_OR_STAND ASC)
	   --,COVID_RESULT_TIME = (SELECT TOP 1 RESULT_TIME FROM #cov c WHERE C.PAT_ID = pat.PAT_ID AND c.ORDERING_DATE <= oc.SURGERY_DATE ORDER BY c.ORDERING_DATE DESC, c.FUTURE_OR_STAND ASC)
	   ----, covid.ORDERING_DATE COVID_ORDERING_DATE
	   ----, covid.RESULT_TIME COVID_RESULT_TIME
FROM CLARITY.dbo.OR_CASE AS oc

INNER JOIN
(
SELECT
	csaseq.OR_CASE_ID,
    csaseq.UPDATE_DATE
FROM
(
SELECT
	csa.OR_CASE_ID,
    csa.UPDATE_DATE,
	ROW_NUMBER() OVER(PARTITION BY csa.OR_CASE_ID ORDER BY csa.UPDATE_DATE DESC) AS updseq
FROM
(
SELECT csa.OR_CASE_ID
             , csa._UPDATE_DT AS UPDATE_DATE
			FROM CLARITY.EPIC_UTIL.CSA_OR_CASE AS csa
			WHERE csa._UPDATE_DT >= CONVERT(DATE,DATEADD(dd,-@LookBackDays,GETDATE()))
			GROUP BY csa.OR_CASE_ID, csa._UPDATE_DT
) csa
) AS csaseq
WHERE csaseq.updseq = 1
) AS x
  ON x.OR_CASE_ID = oc.OR_CASE_ID
    LEFT OUTER JOIN CLARITY.dbo.PAT_OR_ADM_LINK AS a
        ON oc.OR_CASE_ID = a.OR_CASELOG_ID
    LEFT OUTER JOIN CLARITY.dbo.OR_CASE_ALL_PROC AS ocap
        ON ocap.OR_CASE_ID = oc.OR_CASE_ID
    LEFT OUTER JOIN CLARITY.dbo.OR_PROC AS op
        ON op.OR_PROC_ID = ocap.OR_PROC_ID
    LEFT OUTER JOIN CLARITY.dbo.OR_CASE_ALL_SURG AS surg
        ON surg.OR_CASE_ID = oc.OR_CASE_ID AND surg.PANEL = ocap.PANEL
    LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER AS surg_ser
        ON surg_ser.PROV_ID = surg.SURG_ID 
	LEFT OUTER JOIN CLARITY.dbo.OR_CASE_SCHED_HIST ocat ON ocat.OR_CASE_ID = oc.OR_CASE_ID 
		AND ocat.LINE = (SELECT MAX(LINE) FROM CLARITY.dbo.OR_CASE_SCHED_HIST ocat2  
											WHERE ocat2.OR_CASE_ID = ocat.OR_CASE_ID)
    LEFT OUTER JOIN CLARITY.dbo.PATIENT AS pat
        ON pat.PAT_ID = a.PAT_ID
    LEFT OUTER JOIN CLARITY.dbo.PAT_ENC AS enc
        ON enc.PAT_ENC_CSN_ID = a.OR_LINK_CSN
    LEFT OUTER JOIN CLARITY.dbo.OR_LOC AS oloc
        ON oloc.LOC_ID = oc.LOC_ID
    LEFT OUTER JOIN CLARITY.dbo.CLARITY_LOC AS loc
        ON loc.LOC_ID = oloc.LOC_ID
	LEFT JOIN #MDM_REV_LOC_ID AS mloC ON mloc.REV_LOC_ID = LOC.LOC_ID		--Location Update	
    LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP AS emp
        ON emp.USER_ID = oc.REC_CREATE_USER_ID
		LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP AS sched_usr ON sched_usr.USER_ID = ocat.HIST_SCHED_USER_ID
    LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER AS pser
        ON pser.PROV_ID = oc.PRIMARY_PHYSICIAN_ID
    LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER u_ser ON u_ser.USER_ID = oc.REC_CREATE_USER_ID 
	--LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER_DEPT sdep ON sdep.PROV_ID = u_ser.PROV_ID 
	----AND (sdep.INACT_CAD_DEPT_YN = 'N' OR sdep.INACT_CAD_DEPT_YN IS NULL)
	--LEFT OUTER JOIN CLARITY..CLARITY_DEP prov_dep ON sdep.DEPARTMENT_ID = prov_dep.DEPARTMENT_ID
    LEFT OUTER JOIN CLARITY.dbo.ZC_OR_SCHED_STATUS AS zos
        ON zos.SCHED_STATUS_C = oc.SCHED_STATUS_C
	--LEFT OUTER JOIN #cov covid ON covid.PAT_ID = pat.PAT_ID AND covid.ORDERING_DATE <= oc.SURGERY_DATE AND covid.rn = 1
WHERE 1 = 1
      --AND CONVERT(DATE,oc.SURGERY_DATE) >= @StartDate
      --AND CONVERT(DATE,oc.SURGERY_DATE) < DATEADD(d, 1, @EndDate)
	   --AND oc.SURGERY_DATE >= @StartDate
    --   AND oc.SURGERY_DATE < @EndDate + 1
	  --AND sdep.DEPARTMENT_ID IN ('10242006','10354035','10228001','10228003')
	  --AND (0 IN (SELECT ID from @tab_emp) OR ocat.HIST_SCHED_USER_ID in (SELECT ID from @tab_emp))
--AND oc.SCHED_STATUS_C IN ( 1, 8 )
--ORDER BY oc.OR_CASE_ID
AND
			(
    (UPPER(@de_control)=coalesce(UPPER(mloc.de_hospital_code),'UVA-MC'))
    OR (UPPER(@de_control)=coalesce(UPPER(mloc.hospital_group),'UVA-MC'))
    OR (UPPER(@de_control)='ALL')
)
--AND oloc.LOC_ID
--IN (
--'1071024300',	--	UVHE Main OR
--'1071035400'	--	UVBB Outpatient Surgery Center
--)
--AND FLOOR((CAST (oc.SURGERY_DATE AS INTEGER) - CAST(pat.BIRTH_DATE AS INTEGER)) / 365.25) < 18
--AND oc.OR_CASE_ID = '542450'
--AND zos.SCHED_STATUS_C = '1'	--Scheduled
--AND surg_ser.PROV_ID IN (@Surgeon)
AND ocap.LINE = 1
AND zos.NAME NOT IN ('Canceled','Not Scheduled')
--ORDER BY oc.SURGERY_DATE, pat.PAT_MRN_ID--, ocap.LINE
ORDER BY pat.PAT_MRN_ID, oc.SURGERY_DATE