/******	Ref_MDM_Location_Master
1.		Epic Department-level "location" attributes
2.		Includes LOC_ID
3.		MDM (Master Data Management) reporting location hierarchy/grouper values maintained by Data Governance/Data Operations
4.		This version does not retain history, departments deleted in Epic will be removed from
******/
SELECT 
       [LOC_ID]
      ,[REV_LOC_NAME]
      ,[HS_AREA_ID]		/*			Legacy values used to differentiate between Medical Center and non-Medical Center entities	*/
      ,[HS_AREA_NAME]
      ,[PFA_POD]
      ,[HUB]
      ,[PBB_POD]
      ,[POD_ID]
      ,[HUB_ID]
	  ,[EPIC_DEPARTMENT_ID]
      ,[EPIC_DEPT_NAME]
      ,[EPIC_EXT_NAME]
      ,[EPIC_DEPT_TYPE]
      ,[EPIC_SPCLTY]
      ,[FINANCE_COST_CODE]
      ,[PEOPLESOFT_NAME]
      ,[SERVICE_LINE_ID]
      ,[SERVICE_LINE]
      ,[SUB_SERVICE_LINE_ID]
      ,[SUB_SERVICE_LINE]
      ,[RL_LOCATION]
      ,[TELETRACKING_NAME]
      ,[A2K3_NAME]
      ,[A2K3_CLINIC_CARE_AREA_DESCRIPTION]
      ,[AMB_PRACTICE_GROUP]
      ,[NDNQI_NAME]
      ,[NHSN_NAME]
      ,[PRACTICE_GROUP_ID]
      ,[PRACTICE_GROUP_NAME]
      ,[OPNL_SERVICE_ID]
      ,[OPNL_SERVICE_NAME]
      ,[PRESSGANEY_NAME]
      ,[RSS_GROUP]
      ,[RSS_LOCATION]
      ,[DIVISION_CODE]
      ,[DIVISION_DESC]
      ,[ADMIN_CODE]
      ,[ADMIN_DESC]
      ,[BUSINESS_UNIT]
      ,[RPT_RUN_DT]
      ,[MDM_BATCH_ID]
      ,[Load_Dtm]
      ,[CORP_SERVICE_LINE_ID]
      ,[CORP_SERVICE_LINE]
      ,[HAND_HYGIENE]
      ,[PG_SURVEY_DESIGNATOR]
      ,[UPG_PRACTICE_FLAG]
      ,[UPG_PRACTICE_REGION_ID]
      ,[UPG_PRACTICE_REGION_NAME]
      ,[UPG_PRACTICE_ID]
      ,[UPG_PRACTICE_NAME]
      ,[UV_SERVICE_LINE_DIVISION_ID]
      ,[UV_SERVICE_LINE_DIVISION_NAME]
      ,[TJC_FLAG]
      ,[GLKEY_MPIIDTYPE]
      ,[CH_MPIIDTYPE]
      ,[HOSPITAL_CODE]
      ,[LOC_RPT_GRP_NINE_NAME]
      ,[LOC_RPT_GRP_NINE]
  FROM [CLARITY_App].[dbo].[Ref_MDM_Location_Master]
  --ORDER BY LOC_ID
  ORDER BY EPIC_DEPARTMENT_ID