/****** Script for SelectTopNRows command from SSMS  ******/

USE CLARITY
SELECT [PAT_ID]
      ,[PAT_ENC_CSN_ID]
      ,[CONTACT_DATE]
      ,[ENC_TYPE_C]
      ,[ENC_TYPE_TITLE]
	  ,zdet.NAME AS ENC_TYPE_NAME
      ,[VISIT_PROV_ID]
      ,[VISIT_PROV_TITLE]
      ,enc.[DEPARTMENT_ID]
	  ,dep.DEPARTMENT_NAME
      ,[HOSP_ADMSN_TIME]
      ,[HOSP_DISCHRG_TIME]
      ,[HOSP_ADMSN_TYPE_C]
      ,[REFERRAL_REQ_YN]
      ,[REFERRAL_ID]
      ,[HSP_ACCOUNT_ID]
      ,[ADM_FOR_SURG_YN]
      ,[SURGICAL_SVC_C]
      ,[INPATIENT_DATA_ID]
      ,[IP_EPISODE_ID]
      ,[ATTND_PROV_ID]
      ,[REFERRAL_SOURCE_ID]
      ,[ORDERING_PROV_ID]
      ,[EFFECTIVE_DATE_DT]
      ,[DISCHARGE_DATE_DT]
      ,[EFFECTIVE_DEPT_ID]
  FROM [CLARITY].[dbo].[PAT_ENC] enc
  LEFT OUTER JOIN CLARITY.dbo.CLARITY_DEP dep
	ON dep.DEPARTMENT_ID = enc.DEPARTMENT_ID
  LEFT OUTER JOIN CLARITY.dbo.ZC_DISP_ENC_TYPE zdet
	ON zdet.DISP_ENC_TYPE_C = enc.ENC_TYPE_C
  WHERE 1 = 1
  --AND dep.DEPARTMENT_NAME LIKE 'UVHE%'
  AND CONTACT_DATE >= '1/1/2024'
  --AND [REFERRAL_ID] IS NOT NULL 
  --AND [REFERRAL_ID] = 14542112 
  AND [HOSP_ADMSN_TIME] IS NOT NULL
  --AND [REFERRAL_ID] IN (13838947,14055592)