USE CLARITY

SELECT DISTINCT
	rship.GUAR_REL_TO_PAT_C,
	rel.NAME,
	rel.ABBR
FROM CLARITY.dbo.ACCOUNT gacc
LEFT OUTER JOIN CLARITY.dbo.ACCT_GUAR_PAT_INFO rship	ON rship.ACCOUNT_ID = gacc.ACCOUNT_ID
LEFT OUTER JOIN CLARITY.dbo.ZC_GUAR_REL_TO_PAT rel		ON rel.GUAR_REL_TO_PAT_C = rship.GUAR_REL_TO_PAT_C	
ORDER BY
	rship.GUAR_REL_TO_PAT_C