USE CLARITY

SELECT
	guar.ACCT_ID,
	guar.MYPT_ID,
	pyc.PAT_ID,
	guar.EMAIL_ADDRESS,
	pt.PAT_MRN_ID
FROM dbo.ACCOUNT_2 guar
LEFT OUTER JOIN dbo.MYC_PATIENT pyc
	ON pyc.MYPT_ID = guar.MYPT_ID
LEFT OUTER JOIN dbo.PATIENT pt
	ON pt.PAT_ID = pyc.PAT_ID
WHERE guar.MYPT_ID IS NOT NULL
OR guar.EMAIL_ADDRESS IS NOT NULL