USE [CDW_App]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--ALTER   PROCEDURE [ETL].[uspSrc_DAR_Rad_Onc_Referral_to_Consult]
--(
--    @StartDate AS SMALLDATETIME = NULL,
--    @EndDate AS SMALLDATETIME = NULL
--)
--AS

/*****************************************************************************************************************************
WHAT:	[CDW_App].[ETL].[uspSrc_DAR_Rad_Onc_Referral_to_Consult]
WHO :	Monica Seale (MSF8H)
WHEN:	02/03/2025
WHY :	Feature #52363:  DAR FY25 (Rad Onc) Date of Call to Date of Visit
-----------------------------------------------------------------------------------------------------------------------------
INFO: 
	INPUTS:

		[CDW_App].[Rptg].[vwRef_MDM_Location_Master_History]
		[CDW_App].[Rptg].[vwDim_Date]

		[CDW].[FullAccess].[VisitReferralMappingFact]
		[CDW].[FullAccess].[VisitFact]
		[CDW].[FullAccess].[ReferralFact]
		[CDW].[FullAccess].[ProcedureDim]
		[CDW].[FullAccess].[PatientDim]
		[CDW].[FullAccess].[DurationDim]
		[CDW].[FullAccess].[DepartmentDim]
		[CDW].[FullAccess].[ProviderDim]

		[CDW_App].[Rptg].[vwDim_Clrt_SERsrc]
		[CDW_App].[Rptg].[vwRef_OracleOrg_to_EpicFinancialSubdiv]

	OUTPUTS:

		Tab Table:
		
			[DS_HSDM_APP].[TabRptg].[Dash_DAR_Rad_Onc_Referral_to_Consult_Tiles]
   
    NOTES:  

		Radiation Oncology DAR FY25 Goal:

			Schedule 65% of patients within 14 days from date of call to date of visit. 

		Metric ID 967:		Referral to Consult, Rate

		Metric Description:	The percentage of patients who were scheduled for a consult appointment within 14 business days
							from being referred to Radiation Oncology.

		Calculation:  
		
			SQL:  ((SUM(tab.event_count) * 1.0) / COUNT(tab.event_id)) * 100

		Definitions:

		FirstEncounterInstant = First Scheduled, Non-Canceled Appointment Date.

		CreationToFirstEncounterDate = Number of business days between the Referral Creation Date (event_date column)
		and the First Scheduled, Non-Canceled Appointment Date (FirstEncounterInstant column).

		AppointmentInstant = First Scheduled Appointment Date.
		Canceled appointments are included except for ones which were canceled in error (Cancellation Reason = “Error”).

		CreationToFirstApptDate_WithCanceled = Number of business days (weekdays excluding holidays) between the
		Referral Creation Date (event_date column) and the earliest date between the First Scheduled Appointment Date
		(AppointmentInstant column) and the First Scheduled, Non-Canceled Appointment Date (FirstEncounterInstant column).

-----------------------------------------------------------------------------------------------------------------------------
MODS:  02/05/2025 - MSF8H:  1)  Added "Completed" Referral Status per feedback from Joe Mouton.
							2)  Added columns:  EncounterEpicCsn, referral_status, and referral_status_reason.
							3)  Per Melody Shifflett:
								A)  Added "Pending Review" Referral Status.
								B)  Excluded referral orders for AMB REFERRAL TO HEMATOLOGY ONCOLOGY (REF33) [107].
								C)  Added MOSER RONC-GAMMA,SECONDARY [11701288] as an included Visit Type.
							4)  Removed is_within_14_business_days.
							5)  Modified logic for setting event_count.
							6)  Modified peds to be based on the patient's age as of the Consult Visit date.
	   03/04/2025 - MSF8H:  1)  Switched to CDW_App version of materialized views previously only available in CDW_App_Dev.
									[CDW_App].[Rptg].[vwDim_Clrt_SERsrc]
									[CDW_App].[Rptg].[vwRef_OracleOrg_to_EpicFinancialSubdiv]
							2)  Switched from [CDW_App].[dbo].[Dim_Date] to [CDW_App].[Rptg].[vwDim_Date].
							3)  Per Bryan Dunn, added PAT_ID so can pull in sk_Dim_Pt.
							4)  Added the following columns:
									GeneratedByOrder_YesNo
									AppointmentSerialNumber
									AppointmentInstant
									AppointmentStatus
									RescheduledVisitKey
									CancellationInstant
									ReasonAppointmentCanceled
									CancellationInitiator
									CreationToFirstApptDate_WithCanceled
							5)  Modified logic for event_count to be based on CreationToFirstApptDate_WithCanceled instead of
								CreationToFirstEncounterDate.
							6)  Renamed Priority to referral_priority.
							7)  Modified to include referrals which are not generated by a procedure order.
	   03/20/2025 - MSF8H:  Updated primary procedures associated with the referral which should be included.
*****************************************************************************************************************************/

BEGIN
    SET NOCOUNT ON;

	--/*
    -- For testing.
    DECLARE @StartDate AS SMALLDATETIME = NULL,
            @EndDate AS SMALLDATETIME = NULL;

    SET @StartDate = '2024-07-01 00:00:00';
    -- Add 1 day to the desired End Date since using Less Than (<).
    SET @EndDate = '2025-07-01 00:00:00';
    --*/

    ---------------------------------------------------
    -- Get default Balanced Scorecard date range.
    IF @StartDate IS NULL
       AND @EndDate IS NULL
        EXEC [CDW_App].[ETL].[usp_Get_Dash_Dates_BalancedScorecard] @StartDate OUTPUT,
                                                                    @EndDate OUTPUT;
    ----------------------------------------------------
    -- Local variables used to avoid parameter sniffing in SQL Server.
    DECLARE @locStartDate AS SMALLDATETIME = @StartDate,
            @locEndDate AS SMALLDATETIME = @EndDate;
    --------------------------------------------------------------------

    /*
	-- For testing.
	SELECT @StartDate		AS [StartDate],
		   @EndDate			AS [EndDate],
		   @locStartDate	AS [locStartDate],
		   @locEndDate		AS [locEndDate];
	*/

    --------------------------------------------------
    -- For testing.
	-- Drop Temp Tables
    --------------------------------------------------
	--/*

	IF OBJECT_ID('tempdb..#mdm ') IS NOT NULL
		DROP TABLE #mdm
	IF OBJECT_ID('tempdb..#ref ') IS NOT NULL
		DROP TABLE #ref
	IF OBJECT_ID('tempdb..#refpts ') IS NOT NULL
		DROP TABLE #refpts
	IF OBJECT_ID('tempdb..#surgical_procedures ') IS NOT NULL
		DROP TABLE #surgical_procedures
	--IF OBJECT_ID('tempdb..#coded_procedures ') IS NOT NULL
	--	DROP TABLE #coded_procedures
	IF OBJECT_ID('tempdb..#billed_procedures ') IS NOT NULL
		DROP TABLE #billed_procedures
	IF OBJECT_ID('tempdb..#performed_procedures ') IS NOT NULL
		DROP TABLE #performed_procedures
	IF OBJECT_ID('tempdb..#diagnostic_or_treatment_measures ') IS NOT NULL
		DROP TABLE #diagnostic_or_treatment_measures
	IF OBJECT_ID('tempdb..#billed_total_counts ') IS NOT NULL
		DROP TABLE #billed_total_counts
	IF OBJECT_ID('tempdb..#billed_total_charges ') IS NOT NULL
		DROP TABLE #billed_total_charges

	--*/

    --------------------------------------------------
    -- Temp Table:  mdm
    --------------------------------------------------
    SELECT DISTINCT
           rmlmh.EPIC_DEPARTMENT_ID,
           hx.max_dt,
           rmlmh.EPIC_DEPT_NAME,
           rmlmh.EPIC_EXT_NAME,
           rmlmh.EPIC_DEPT_TYPE,
           rmlmh.HS_AREA_ID,
           rmlmh.HS_AREA_NAME,
           rmlmh.HOSPITAL_CODE,
           rmlmh.EPIC_SPCLTY

    INTO #mdm

    FROM [CDW_App].[Rptg].[vwRef_MDM_Location_Master_History] AS rmlmh

        INNER JOIN
        ( --hx--most recent batch date per dep id
            SELECT mdmhx.EPIC_DEPARTMENT_ID,
                   MAX(mdmhx.BATCH_RUN_DT) AS max_dt

            FROM [CDW_App].[Rptg].[vwRef_MDM_Location_Master_History] AS mdmhx

            GROUP BY mdmhx.EPIC_DEPARTMENT_ID
        ) AS hx
            ON hx.EPIC_DEPARTMENT_ID = rmlmh.EPIC_DEPARTMENT_ID
               AND rmlmh.BATCH_RUN_DT = hx.max_dt;

    -- For testing.
    /*
	SELECT mdm.*
	FROM #mdm mdm
	*/

    --------------------------------------------------
	-- Temp Table:  ref
    --------------------------------------------------
    SELECT ref.PatientDurableKey,
           --ref.AgeKey,
           --ref.DepartmentKey,
           --ref.PrimaryVisitProviderDurableKey,
           ref.ReferralEpicId,
           ref.CreationInstant,
           ref.referral_type,
		   ref.ReferralType,
           ref.Class,
           ref.referral_status,
           ref.referral_status_reason,
           ref.referral_priority,
           ref.GeneratedByOrder_YesNo,
           --ref.ProcedureOrderEpicId,
           --ref.proc_code,
           --ref.proc_name,
           --ref.VisitTypeEpicId,
           --ref.VisitType,
           --ref.EncounterEpicCsn,
           --ref.encounter_type,
           --ref.AppointmentSerialNumber,
           --ref.AppointmentInstant,
           --ref.AppointmentStatus,
           --ref.RescheduledVisitKey,
           --ref.CancellationInstant,
           --ref.ReasonAppointmentCanceled,
           --ref.CancellationInitiator,
           ref.FirstEncounterInstant,
           ref.CreationToFirstEncounterDate,
           --ref.appt_order
		   ref.rflseq,
		   ref.PAT_ID,
		   ref.person_id

    INTO #ref

    FROM
    (
        SELECT DISTINCT
               -- Surrogate keys used later for joining to Dim tables.
               ref.PatientDurableKey,
               --vst.AgeKey,
               --vst.DepartmentKey,
               --vst.PrimaryVisitProviderDurableKey,

               ref.ReferralEpicId,			-- event_id
               ref.CreationInstant,			-- event_date
               ref.Type AS [referral_type],
			   auth.ReferralType,
               ref.Class,					-- event_category
               ref.Status AS [referral_status],
               ref.StatusReason AS [referral_status_reason],
               ref.Priority AS [referral_priority],
               ref.GeneratedByOrder_YesNo,
			   --pof.ProcedureOrderEpicId,
      --         prc.Code AS [proc_code],
      --         prc.Name AS [proc_name],
			   -- Used to later identify Consult Visits.
               --vst.VisitTypeEpicId,
               --vst.VisitType,
               --vst.EncounterEpicCsn,
               --vst.EncounterType AS [encounter_type],

               --vst.AppointmentSerialNumber,
               --vst.AppointmentInstant,
               --vst.AppointmentStatus,
               -- Non-canceled appointment rescheduled from this visit.
               --vst.RescheduledVisitKey,
               --vst.CancellationInstant,
               --vst.ReasonAppointmentCanceled,
               --vst.CancellationInitiator,

               ref.FirstEncounterInstant,
               ref.CreationToFirstEncounterDate,
			   -- Patient
			   CAST(pat.BirthDate AS DATETIME) AS [person_birth_date],
			   CAST(pat.Sex AS VARCHAR(255)) AS [person_gender],
		       CAST(pat.PatientEpicId AS VARCHAR(18)) AS [PAT_ID],
			   TRY_CAST(pat.PrimaryMrn AS INT) AS [person_id],
			   CAST(pat.Name AS VARCHAR(200)) AS [person_name],

               --ROW_NUMBER() OVER (PARTITION BY ref.ReferralKey
               --                   ORDER BY vst.AppointmentSerialNumber ASC,
               --                            vst.RescheduledVisitKey DESC,
               --                            vst.CancellationInstant ASC
               --                  ) AS [appt_order]
			   ROW_NUMBER() OVER(PARTITION BY auth.PatientDurableKey ORDER BY ref.CreationInstant) AS rflseq

		FROM [CDW].[FullAccess].[ReferralFact] ref
/*
        FROM [CDW].[FullAccess].[VisitReferralMappingFact] map

            INNER JOIN [CDW].[FullAccess].[VisitFact] vst
                ON map.VisitKey = vst.VisitKey
                   AND vst.Count = 1

            INNER JOIN [CDW].[FullAccess].[ReferralFact] ref
                ON map.ReferralKey = ref.ReferralKey
                   AND ref.Count = 1

            -- Use LEFT OUTER JOIN since not all referrals are generated by a procedure order.
            LEFT OUTER JOIN [CDW].[FullAccess].[ProcedureOrderFact] pof
                ON ref.GeneratedByOrderKey = pof.ProcedureOrderKey
                   AND pof.Count = 1

            LEFT OUTER JOIN [CDW].[FullAccess].[ProcedureDim] prc
                ON ref.PrimaryProcedureDurableKey = prc.DurableKey
                   AND prc.IsCurrent = 1

*/

		LEFT OUTER JOIN CDW.FullAccess.AuthorizationFact auth
			ON auth.ReferralKey = ref.ReferralKey
				AND auth.Count = 1

        INNER JOIN [CDW].[FullAccess].[PatientDim] pat
            ON ref.PatientDurableKey = pat.DurableKey
                AND pat.IsCurrent = 1
                AND pat.IsValid = 1
                AND pat.IsHistoricalPatient = 0
                AND pat.Test = 0
                AND pat.DurableKey <> 15282261 /* ANONYMOUS HIM ONLY,REG IN ERROR TESTPATIENTS MRN 4233223 */

        --INNER JOIN [CDW].[FullAccess].[DurationDim] age
        --    ON ref.AgeKey = age.DurationKey

        WHERE 1 = 1

              --AND map.HasErrors = 0

              --AND map.Count = 1

              AND ref.Count = 1

              --------------------------------------------------
              -- Referral criteria
              --------------------------------------------------

              AND ref.CreationInstant >= @locStartDate
              AND ref.CreationInstant < @locEndDate

			  --AND ref.Class IN ( 'Internal', 'Incoming' )
			  AND ref.Class = 'Incoming'

              --AND
              --(
              --    -- Results are combined from both the Referred To Department Specialty and the Referred To Provider Specialty.
              --    ref.ReferredToSpecialty = 'Radiation Oncology'
              --    -- Added to make certain that all referrals to Radiation Oncology are included.
              --    OR ref.ReferredToDepartmentSpecialty = 'Radiation Oncology'
              --    OR ref.ReferredToProviderSpecialty = 'Radiation Oncology'
              --)

              -- Referral Status
              --AND ref.Status IN ( 'Authorized', 'Closed', 'Completed', 'Pending Review' )

              -- The LinkedToAnEncounter column stores a 1 value once the referral is linked to a scheduled, non-canceled encounter.
              -- It does not require that the encounter actually occur. This indicates that the patient and the organization made progress
              -- with the referral and continuing care.
              --AND ref.LinkedToAnEncounter = 1

			  --AND
			  --(

				 -- ref.PrimaryProcedureDurableKey    = 37413		-- RADIATION ONCOLOGY EVALUATION (RAD3) [40241] - RADIATION ONCOLOGY ORDERABLES
				 -- OR ref.PrimaryProcedureDurableKey = 20513		-- AMB REFERRAL TO RADIATION ONCOLOGY (REF95) [231] - OUTPATIENT REF ORDERABLES UVA
				 -- OR ref.PrimaryProcedureDurableKey = 163894	-- RADIATION THERAPY (SHX1077062) [209846] - GENERIC SURGICAL HISTORY
				 -- OR ref.PrimaryProcedureDurableKey = -1		-- *Unspecified
			  --)

              --------------------------------------------------
              -- Consult Visit criteria
              --------------------------------------------------

              --AND
              --(
              --    -- Emily Couric Cancer Center (ECCC)
              --    vst.VisitTypeEpicId    = '11701282' -- RADONC CONS - GAMMA, SECONDARY [11701282]
              --    OR vst.VisitTypeEpicId = '11701279' -- RADONC CONS - GYN,GU,PONC,SARC [11701279]
              --    OR vst.VisitTypeEpicId = '11701281' -- RADONC CONS - HEADNECK, SKIN CA [11701281]
              --    OR vst.VisitTypeEpicId = '11701280' -- RADONC CONSULT - CNS AND LUNG [11701280]
              --    OR vst.VisitTypeEpicId = '11701283' -- RADONC CONSULT - GENERAL [11701283]
              --    OR vst.VisitTypeEpicId = '11701278' -- RADONC CONSULT - GI AND BREAST [11701278]
              --    OR vst.VisitTypeEpicId = '11703517' -- RADONC CONSULT EXTENDED [11703517]

              --    -- Moser Radiation Therapy Center
              --    OR vst.VisitTypeEpicId = '11701286' -- MOSER RONC CON-CNS/LUNG [11701286]
              --    OR vst.VisitTypeEpicId = '11701285' -- MOSER RONC CON-GYN,GU,PONC,SAR [11701285]
              --    OR vst.VisitTypeEpicId = '11701287' -- MOSER RONC CON-HEADNECK/SKIN [11701287]
              --    OR vst.VisitTypeEpicId = '11701284' -- MOSER RONC CONSULT - GI/BREAST [11701284]
              --    OR vst.VisitTypeEpicId = '11701289' -- MOSER RONC CONSULT - RAD ONC [11701289]
              --    OR vst.VisitTypeEpicId = '11701288' -- MOSER RONC-GAMMA,SECONDARY [11701288]
              --)

              --AND vst.ReasonAppointmentCanceled <> 'Error'

			  AND (ref.NumberOfCompletedVisits_X IS NOT NULL AND ref.NumberOfCompletedVisits_X > 0)

			  AND ref.TYPE NOT IN ('Home Health Care', 'Home Health Pharmacy', 'Home Health Visits', 'Insurance Referral', 'Lab', 'NonTOC Order', 'PFA Appointment Request', 'Treatment Plan')

    ) ref

    WHERE 1 = 1

        --AND ref.appt_order = 1;

	ORDER BY
		ref.PatientDurableKey,
		ref.rflseq

-- Create index for temp table #ref
	CREATE CLUSTERED INDEX IX_ref ON #ref (PatientDurableKey, rflseq)

		--SELECT
		--	*
		--FROM #ref
		--ORDER BY
		--    referral_type,
		--    ReferralType,
		--	CreationInstant,
		--	PatientDurableKey

		--SELECT DISTINCT
		--	referral_type,
		--	ReferralType
		--FROM #ref
		--ORDER BY
		--    referral_type,
		--    ReferralType

	SELECT --DISTINCT
		PatientDurableKey,
		PAT_ID,
		person_id,
		CreationInstant -- Referral entry date
	INTO #refpts
	FROM #ref
	WHERE rflseq = 1 -- Earliest referral entry date for a patient
	ORDER BY
		PatientDurableKey

	-- Create index for temp table #refpts

	CREATE CLUSTERED INDEX IX_refpts ON #refpts (PatientDurableKey)

	--SELECT
	--	PatientDurableKey,
	--	PAT_ID,
	--	person_id,
 --       CreationInstant
	--FROM #refpts
	--ORDER BY
	--	PatientDurableKey

--DROP TABLE IF EXISTS #surgical_procedures;
/**  surgical procedures **/
SELECT 'CPT' AS CodeSet
      ,br.Code
      ,br.Name
      ,spef.SurgeryDateKey
      ,spef.PatientDurableKey
      ,spef.HospitalEncounterKey
      ,enc_hsp.EncounterEpicCsn AS HospitalEncounterEpicCsn
      ,spef.SurgeryEncounterKey
      ,enc_surgery.EncounterEpicCsn AS SurgeryEncounterEpicCsn
      ,dept.RoomName
      ,dept.DepartmentName
      ,dept.DepartmentEpicId DepartmentID
      ,spef.PrimarySurgeonDurableKey
      ,prov.ProviderEpicId ProviderID
--, trim(map.Workbook_Sheet)     AS Workbook_Sheet
      --,enc_hsp.PrimaryProcedureDurableKey
	  --,enc_hsp.EncounterKey AS enc_hsp_EncounterKey
	  --,enc_surgery.EncounterKey
	  ,baf.BillingAccountKey
	  ,baf.TotalChargeAmount
INTO #surgical_procedures
FROM CDW.FullAccess.SurgicalProcedureEventFact AS spef
    INNER JOIN CDW.FullAccess.SurgicalProcedureCodeBridge AS br
        ON spef.ProcedureCodeComboKey = br.SurgicalProcedureCodeComboKey
    INNER JOIN CDW.FullAccess.SurgicalCaseFact AS scf
        ON spef.SurgicalCaseKey       = scf.SurgicalCaseKey
    INNER JOIN CDW.FullAccess.DurationDim AS age
        ON spef.AgeKey                = age.DurationKey
    INNER JOIN #refpts AS rfls
        ON spef.PatientDurableKey = rfls.PatientDurableKey
		AND scf.ProcedureCompleteInstant > rfls.CreationInstant
    INNER JOIN CDW.FullAccess.SourceDim AS sd
        ON spef.SourceKey             = sd.SourceKey
    INNER JOIN CDW.FullAccess.DepartmentDim AS dept
        ON spef.OperatingRoomKey      = dept.DepartmentKey
    INNER JOIN CDW.FullAccess.DateDim AS surgery_dte
        ON spef.SurgeryDateKey        = surgery_dte.DateKey
    INNER JOIN CDW.FullAccess.EncounterFact AS enc_hsp
        ON spef.HospitalEncounterKey  = enc_hsp.EncounterKey
    INNER JOIN CDW.FullAccess.EncounterFact AS enc_surgery
        ON spef.SurgeryEncounterKey   = enc_surgery.EncounterKey
	LEFT OUTER JOIN CDW.FullAccess.BillingAccountFact baf
		ON enc_hsp.EncounterKey = baf.PrimaryEncounterKey
    INNER JOIN CDW_App.Rptg.vwRef_MDM_Location_Master_Hospital_Group_ALL AS mdm
        ON dept.DepartmentEpicId      = CONVERT(NVARCHAR(18), mdm.EPIC_DEPARTMENT_ID)
    INNER JOIN CDW.FullAccess.ProviderDim AS prov
        ON prov.DurableKey            = spef.PrimarySurgeonDurableKey
           AND prov.IsCurrent         = 1
           AND prov.DurableKey        > 0
WHERE 1                             = 1
      AND mdm.DE_HOSPITAL_CODE      = 'UVA-MC'
      AND spef.Count              = 1
      AND spef.Performed            = 1
      AND scf.Count               = 1
      AND scf.Canceled              = 0
      AND scf.ProcedureNotPerformed = 0
      AND NOT EXISTS (SELECT enc_hsp.DerivedEncounterStatus INTERSECT SELECT N'Invalid')
      AND enc_hsp.Type NOT LIKE '%erroneous%'
	  AND enc_hsp.IsDerivedFromBilling = 0
	  AND Code <> '*Deleted';
/*
SELECT
    PatientDurableKey,
    SurgeryDateKey,
    BillingAccountKey,
	CodeSet,
    Code,
    Name,
    HospitalEncounterKey,
    HospitalEncounterEpicCsn,
    SurgeryEncounterKey,
    SurgeryEncounterEpicCsn,
    RoomName,
    DepartmentName,
    DepartmentID,
    PrimarySurgeonDurableKey,
    ProviderID,
	--enc_hsp_EncounterKey,
 --   EncounterKey,
    TotalChargeAmount
FROM #surgical_procedures
ORDER BY
	PatientDurableKey,
	SurgeryDateKey,
	BillingAccountKey
*/
/* coded procedures */
--DROP TABLE IF EXISTS #coded_procedures;
/*
SELECT ptd.CodeSet
      ,ptd.Code
      ,ptd.Name
      ,cpf.ProcedureDateKey
      ,baf.PatientDurableKey
      ,baf.AccountEpicId
      ,baf.PrimaryEncounterKey
      ,cpf.PerformingProviderDurableKey
      ,prov.ProviderEpicId ProviderID
      ,dept.DepartmentEpicId DepartmentID
      ,dept.DepartmentName
	  ,ef.EncounterEpicCsn AS HospitalEncounterEpicCsn 
	  --,ef.PrimaryProcedureDurableKey
--, trim(map.Workbook_Sheet) AS Workbook_Sheet
     ,baf.BillingAccountKey
	 ,baf.TotalChargeAmount
INTO #coded_procedures
FROM CDW.FullAccess.CodedProcedureFact AS cpf
    INNER JOIN CDW.FullAccess.ProcedureTerminologyDim AS ptd
        ON cpf.ProcedureTerminologyKey = ptd.ProcedureTerminologyKey
    --INNER JOIN CDW.FullAccess.BillingAccountFact AS baf
    --    ON cpf.BillingAccountKey       = baf.BillingAccountKey
    LEFT OUTER JOIN CDW.FullAccess.BillingAccountFact AS baf
        ON cpf.BillingAccountKey       = baf.BillingAccountKey
	INNER JOIN CDW.FullAccess.EncounterFact AS ef
		ON baf.PrimaryEncounterKey  = ef.EncounterKey
    INNER JOIN CDW.FullAccess.PatientDim AS pat
        ON baf.PatientDurableKey       = pat.DurableKey
           AND pat.IsCurrent           = 1
           AND pat.IsValid             = 1
           AND pat.IsHistoricalPatient = 0
    INNER JOIN #refpts AS rfls
        ON baf.PatientDurableKey = rfls.PatientDurableKey
		AND ef.AdmissionInstant > rfls.CreationInstant
    INNER JOIN CDW.FullAccess.DepartmentDim AS dept
        ON baf.DepartmentKey           = dept.DepartmentKey
    INNER JOIN CDW_App.Rptg.vwRef_MDM_Location_Master_Hospital_Group_ALL AS mdm
        ON dept.DepartmentEpicId       = CONVERT(NVARCHAR(18), mdm.EPIC_DEPARTMENT_ID)
    INNER JOIN CDW.FullAccess.ProviderDim AS prov
        ON prov.DurableKey             = cpf.PerformingProviderDurableKey
           AND prov.IsCurrent          = 1
           AND prov.DurableKey         > 0

-- INNER JOIN #tempDenom     AS ghd
--     ON pat.DurableKey              = ghd.DurableKey
WHERE cpf.Count              = 1
      --AND baf.Count          = 1
	  --AND ef.Count = 1
      AND mdm.DE_HOSPITAL_CODE = 'UVA-MC'
      --AND EXISTS (SELECT NULL FROM #tempDenom AS t WHERE t.DurableKey = pat.DurableKey)
	  AND ef.IsDerivedFromBilling = 0;

SELECT
    PatientDurableKey,
    ProcedureDateKey,
    BillingAccountKey,
	CodeSet,
    Code,
    Name,
    AccountEpicId,
    PrimaryEncounterKey,
    PerformingProviderDurableKey,
    ProviderID,
    DepartmentID,
    DepartmentName,
    HospitalEncounterEpicCsn,
    TotalChargeAmount
FROM #coded_procedures
ORDER BY
	PatientDurableKey,
	ProcedureDateKey,
	BillingAccountKey
*/
/* billed procedures */
--DROP TABLE IF EXISTS #billed_procedures;

SELECT DISTINCT
       ua.CodeSet
      ,ua.CptCode
      ,ua.Name
      ,ua.ServiceDateKey
      ,ua.EncounterKey
      ,ua.PatientDurableKey
      ,ua.BillingAccountKey
      ,ua.AccountEpicId
      ,ua.BillingProcedureQuantity
	  ,ua.ChargeAmount
      ,ua.DepartmentID
      ,ua.AttendingProviderDurableKey
      ,ua.ProviderID
	  ,ua.HospitalEncounterEpicCsn
	  --,ua.PrimaryProcedureDurableKey
	  --,ua.TotalChargeAmount
INTO #billed_procedures
FROM (/* CPT */
         SELECT 'CPT' AS CodeSet
               ,bpd.cptcode
               ,bpd.Name
               ,btf.ServiceDateKey
               ,btf.EncounterKey
               ,btf.PatientDurableKey
               ,baf.BillingAccountKey
               ,baf.AccountEpicId
               ,btf.BillingProcedureQuantity
			   ,btf.ChargeAmount
               ,dept.DepartmentEpicId DepartmentID
               ,baf.AttendingProviderDurableKey
               ,prov.ProviderEpicId ProviderID
			   ,ef.EncounterEpicCsn AS HospitalEncounterEpicCsn
			   --,ef.PrimaryProcedureDurableKey
         --, trim(map.Workbook_Sheet) AS Workbook_Sheet
		       --,baf.TotalChargeAmount
         FROM CDW.FullAccess.BillingTransactionFact AS btf
             INNER JOIN CDW.FullAccess.BillingProcedureDim AS bpd
                 ON btf.BillingProcedureDurableKey = bpd.DurableKey
                    AND bpd.IsCurrent              = 1
             INNER JOIN CDW.FullAccess.BillingAccountFact AS baf
                 ON btf.BillingAccountKey          = baf.BillingAccountKey
             INNER JOIN CDW.fullaccess.encounterfact AS ef
                 ON ef.encounterkey                = btf.encounterkey
			INNER JOIN #refpts AS rfls
				ON btf.PatientDurableKey = rfls.PatientDurableKey
				AND ef.AdmissionInstant > rfls.CreationInstant
             INNER JOIN CDW.FullAccess.DepartmentDim AS dept
                 ON ef.DepartmentKey               = dept.DepartmentKey
             INNER JOIN CDW_App.Rptg.vwRef_MDM_Location_Master_Hospital_Group_ALL AS mdm
                 ON dept.DepartmentEpicId          = CONVERT(NVARCHAR(18), mdm.EPIC_DEPARTMENT_ID)
             INNER JOIN CDW.FullAccess.ProviderDim AS prov
                 ON prov.DurableKey                = baf.AttendingProviderDurableKey
                    AND prov.IsCurrent             = 1
                    AND prov.DurableKey            > 0
             INNER JOIN CDW.FullAccess.PatientDim AS pat
                 ON pat.DurableKey                 = btf.PatientDurableKey

         --  INNER JOIN #tempDenom     AS ghd
         --      ON btf.PatientDurableKey       = ghd.DurableKey

		 
         WHERE 1                                = 1
               --AND EXISTS (SELECT NULL FROM #tempDenom AS t WHERE t.DurableKey = btf.PatientDurableKey)
               AND btf.ReportingTransactionType = N'Charge'
               AND btf.Count                  = 1
               AND baf.Count                  = 1
               AND mdm.DE_HOSPITAL_CODE         = 'UVA-MC'

--AND trim(map.Status) IN ( 'New', 'No change' )
				AND ef.IsDerivedFromBilling = 0
) AS ua;
/*
SELECT
    PatientDurableKey,
    ServiceDateKey,
    BillingAccountKey,
	CodeSet,
    CptCode,
    Name,
    EncounterKey,
    AccountEpicId,
    BillingProcedureQuantity,
    DepartmentID,
    AttendingProviderDurableKey,
    ProviderID,
    HospitalEncounterEpicCsn,
    TotalChargeAmount
FROM #billed_procedures
ORDER BY
	PatientDurableKey,
	ServiceDateKey,
	BillingAccountKey
*/	
/* performed procedures */
--DROP TABLE IF EXISTS #performed_procedures;

SELECT tcd.StandardName AS CodeSet
      ,tcd.Concept AS Code
      ,procd.Name
      ,pef.ProcedureStartDateKey
      ,pef.PatientDurableKey
      ,enc.EncounterEpicCsn AS HospitalEncounterEpicCsn
      ,enc.EncounterKey
      ,dept.DepartmentEpicId DepartmentID
      ,pef.PerformingProviderDurableKey
      ,prov.ProviderEpicId ProviderID
	  --,enc.PrimaryProcedureDurableKey
	  ,baf.BillingAccountKey
	  ,baf.TotalChargeAmount
INTO #performed_procedures
FROM CDW.FullAccess.ProcedureEventFact AS pef
    INNER JOIN CDW.FullAccess.ProcedureDim AS procd
        ON pef.ProcedureDurableKey     = procd.DurableKey
           AND procd.IsCurrent         = 1
    INNER JOIN CDW.FullAccess.ProcedureMappingDim AS pmd
        ON procd.DurableKey            = pmd.ProcedureDurableKey
           AND pmd.IsCurrent           = 1
    INNER JOIN CDW.FullAccess.TerminologyConceptDim AS tcd
        ON pmd.TerminologyConceptKey   = tcd.TerminologyConceptKey

    -- INNER JOIN #tempDenom         AS ghd
    --     ON pef.PatientDurableKey     = ghd.DurableKey

   INNER JOIN CDW.FullAccess.EncounterFact AS enc
        ON pef.EncounterKey            = enc.EncounterKey
	INNER JOIN #refpts AS rfls
		ON pef.PatientDurableKey = rfls.PatientDurableKey
		AND enc.AdmissionInstant > rfls.CreationInstant
    INNER JOIN CDW.FullAccess.DepartmentDim AS dept
        ON enc.AttributedDepartmentKey = dept.DepartmentKey
    INNER JOIN CDW_App.Rptg.vwRef_MDM_Location_Master_Hospital_Group_ALL AS mdm
        ON dept.DepartmentEpicId       = CONVERT(NVARCHAR(18), mdm.EPIC_DEPARTMENT_ID)
    INNER JOIN CDW.FullAccess.ProcedureEventSourceBridge AS br
        ON pef.SourceComboKey          = br.ProcedureEventSourceComboKey
    INNER JOIN CDW.FullAccess.ProviderDim AS prov
        ON prov.DurableKey             = pef.PerformingProviderDurableKey
           AND prov.IsCurrent          = 1
           AND prov.DurableKey         > 0
	LEFT OUTER JOIN CDW.FullAccess.BillingAccountFact baf
		ON enc.EncounterKey = baf.PrimaryEncounterKey
WHERE 1                        = 1
      --AND EXISTS (SELECT NULL FROM #tempDenom AS t WHERE t.DurableKey = pef.PatientDurableKey)
      AND mdm.DE_HOSPITAL_CODE = 'UVA-MC'
      AND pef.Count          = 1
      --AND trim(map.[Type])          = tcd.StandardName
      AND NOT EXISTS (SELECT enc.DerivedEncounterStatus INTERSECT SELECT N'Invalid')
	  AND enc.IsDerivedFromBilling = 0;
--AND enc.[Type] NOT LIKE '%erroneous%';
/*
SELECT
    PatientDurableKey,
    ProcedureStartDateKey,
    BillingAccountKey,
	CodeSet,
    Code,
    Name,
    HospitalEncounterEpicCsn,
    EncounterKey,
    DepartmentID,
    PerformingProviderDurableKey,
    ProviderID,
    TotalChargeAmount
FROM #performed_procedures
ORDER BY
	PatientDurableKey,
	ProcedureStartDateKey,
	BillingAccountKey
*/
/* combine all procedures */
--DROP TABLE IF EXISTS #diagnostic_or_treatment_measures;

SELECT
           'bp' AS ProcSet
          ,bp.CodeSet
          ,bp.CptCode
          ,bp.Name
          ,bp.ServiceDateKey
          ,bp.PatientDurableKey
          ,bp.EncounterKey
          -- , bp.Workbook_Sheet
          ,bp.BillingProcedureQuantity
		  ,bp.ChargeAmount
          ,bp.DepartmentID
          ,bp.ProviderID
		  ,bp.HospitalEncounterEpicCsn
		  --,bp.PrimaryProcedureDurableKey
		  ,bp.BillingAccountKey
          ,SUM(bp.BillingProcedureQuantity) OVER (PARTITION BY
                                                      -- bp.Workbook_Sheet
                                                      bp.PatientDurableKey
                                                     ,bp.CptCode
                                                     ,bp.ServiceDateKey
													 ,bp.BillingAccountKey) AS BilledTotalQuantity
          ,SUM(bp.ChargeAmount) OVER (PARTITION BY
                                                      -- bp.Workbook_Sheet
                                                      bp.PatientDurableKey
                                                     ,bp.CptCode
                                                     ,bp.ServiceDateKey
													 ,bp.BillingAccountKey) AS BilledTotalCharge
	INTO #billed_total_counts
    FROM #billed_procedures AS bp

	SELECT
        billed_total_counts.PatientDurableKey,
        billed_total_counts.CptCode,
        billed_total_counts.ServiceDateKey,
		billed_total_counts.BillingAccountKey,
		billed_total_counts.ProcSet,
        billed_total_counts.CodeSet,
        billed_total_counts.Name,
        billed_total_counts.EncounterKey,
        billed_total_counts.BillingProcedureQuantity,
		billed_total_counts.ChargeAmount,
        billed_total_counts.DepartmentID,
        billed_total_counts.ProviderID,
        billed_total_counts.HospitalEncounterEpicCsn,
        billed_total_counts.BilledTotalQuantity,
        billed_total_counts.BilledTotalCharge
	 FROM #billed_total_counts billed_total_counts
	 ORDER BY
		billed_total_counts.PatientDurableKey,
		billed_total_counts.CptCode,
		billed_total_counts.ServiceDateKey
/*
;WITH billed_total_counts
AS (SELECT
           'bp' AS ProcSet
          ,bp.CodeSet
          ,bp.CptCode
          ,bp.Name
          ,bp.ServiceDateKey
          ,bp.PatientDurableKey
          ,bp.EncounterKey
          -- , bp.Workbook_Sheet
          ,bp.BillingProcedureQuantity
          ,bp.DepartmentID
          ,bp.ProviderID
		  ,bp.HospitalEncounterEpicCsn
		  --,bp.PrimaryProcedureDurableKey
          ,SUM(bp.BillingProcedureQuantity) OVER (PARTITION BY
                                                      -- bp.Workbook_Sheet
                                                      bp.PatientDurableKey
                                                     ,bp.CptCode
                                                     ,bp.ServiceDateKey) AS BilledTotalQuantity
    FROM #billed_procedures AS bp)

	SELECT
        billed_total_counts.PatientDurableKey,
        billed_total_counts.CptCode,
        billed_total_counts.ServiceDateKey,
		billed_total_counts.ProcSet,
        billed_total_counts.CodeSet,
        billed_total_counts.Name,
        billed_total_counts.EncounterKey,
        billed_total_counts.BillingProcedureQuantity,
        billed_total_counts.DepartmentID,
        billed_total_counts.ProviderID,
        billed_total_counts.HospitalEncounterEpicCsn,
        billed_total_counts.BilledTotalQuantity
	 FROM billed_total_counts
	 ORDER BY
		billed_total_counts.PatientDurableKey,
		billed_total_counts.CptCode,
		billed_total_counts.ServiceDateKey
*/

SELECT DISTINCT
       ua.ProcSet
	  ,ua.CodeSet
      ,ua.Code
      ,ua.Name
      ,dd.Year
      ,ua.DateKey
      ,ua.PatientDurableKey
      ,pat.primaryMrn
      ,ua.DepartmentID
      ,ua.ProviderID
	  ,ua.HospitalEncounterEpicCsn
	  --,ua.PrimaryProcedureDurableKey
	  ,ua.BillingAccountKey
	  ,ua.TotalChargeAmount
INTO #diagnostic_or_treatment_measures
FROM (   SELECT
                'sp' AS ProcSet
               ,sp.CodeSet
               ,sp.Code
               ,sp.Name
               ,sp.SurgeryDateKey AS DateKey
               ,sp.PatientDurableKey
               ,sp.DepartmentID
               ,sp.ProviderID
			   ,sp.HospitalEncounterEpicCsn
			   --,sp.PrimaryProcedureDurableKey
			   ,sp.BillingAccountKey
			   ,sp.TotalChargeAmount
         FROM #surgical_procedures AS sp
         UNION ALL
      --   SELECT
      --          'cp' AS ProcSet
      --         ,cp.CodeSet
      --         ,cp.Code
      --         ,cp.Name
      --         ,cp.ProcedureDateKey
      --         ,cp.PatientDurableKey
      --         ,cp.DepartmentID
      --         ,cp.ProviderID
			   --,cp.HospitalEncounterEpicCsn
			   ----,cp.PrimaryProcedureDurableKey
      --   FROM #coded_procedures AS cp
      --   UNION ALL
         SELECT
                btc.ProcSet
               ,btc.CodeSet
               ,btc.CptCode
               ,btc.Name
               ,btc.ServiceDateKey
               ,btc.PatientDurableKey
               ,btc.DepartmentID
               ,btc.ProviderID
			   ,btc.HospitalEncounterEpicCsn
			   --,btc.PrimaryProcedureDurableKey
			   ,btc.BillingAccountKey
			   ,btc.BilledTotalCharge AS TotalChargeAmount 
         --FROM billed_total_counts AS btc
         FROM #billed_total_counts AS btc
         WHERE btc.BilledTotalQuantity > 0
         UNION ALL
         SELECT
                'pp' AS ProcSet
               ,pp.CodeSet
               ,pp.Code
               ,pp.Name
               ,pp.ProcedureStartDateKey
               ,pp.PatientDurableKey
               ,pp.DepartmentID
               ,pp.ProviderID
			   ,pp.HospitalEncounterEpicCsn
			   --,pp.PrimaryProcedureDurableKey
			   ,pp.BillingAccountKey
			   ,pp.TotalChargeAmount
         FROM #performed_procedures AS pp) AS ua
    INNER JOIN CDW.FullAccess.DateDim AS dd
        ON ua.DateKey      = dd.DateKey
    INNER JOIN CDW.FullAccess.PatientDim AS pat
        ON pat.DurableKey  = ua.PatientDurableKey
           AND pat.IsValid = 1;

SELECT --DISTINCT
    PatientDurableKey,
	HospitalEncounterEpicCsn,
	trt.BillingAccountKey,
	trt.TotalChargeAmount,
    DateKey,
    ProcSet,
	trt.CodeSet,
    trt.Code,
	--PrimaryProcedureDurableKey,
	--dim.Code AS PrimaryCode,
	--dim.Name AS PrimaryName,
    trt.Name,
    Year,
    PrimaryMrn,
    DepartmentID,
    ProviderID
FROM #diagnostic_or_treatment_measures trt
--LEFT OUTER JOIN CDW.FullAccess.ProcedureDim dim
--	ON dim.DurableKey = trt.PrimaryProcedureDurableKey
WHERE LEN(trt.Code) > 0
ORDER BY
	PatientDurableKey,
	HospitalEncounterEpicCsn,
	DateKey,
	trt.Code


/*
    --------------------------------------------------
	-- Final output
    --------------------------------------------------
    SELECT DISTINCT

           -- Event columns.
           CAST('Referral' AS VARCHAR(50)) AS [event_type],
           CASE
               --WHEN main.CreationToFirstEncounterDate < 15 THEN
			   WHEN main.CreationToFirstApptDate_WithCanceled < 15 THEN
                   CAST(1 AS INT)
               ELSE
                   CAST(0 AS INT)
           END AS [event_count],                               -- Numerator
           CAST(COALESCE(main.CreationInstant, dt.day_date) AS SMALLDATETIME) AS [event_date],
           TRY_CAST(main.ReferralEpicId AS INT) AS [event_id], -- Denominator
           CAST(main.Class AS VARCHAR(50)) AS [event_category],

           -- Date columns.
           CAST(dt.fmonth_num AS INT) AS [fmonth_num],
           CAST(dt.Fyear_num AS INT) AS [fyear_num],
           CAST(dt.FYear_name AS VARCHAR(50)) AS [fyear_name],

           -- Main
           main.person_birth_date,
           main.person_gender,
           main.person_id,
           main.person_name,
           COALESCE(main.peds, CAST(0 AS INT)) AS [peds],
           main.epic_department_id,
           main.epic_department_name,
           main.epic_department_name_external,
           main.provider_id,
           main.provider_name,
           main.prov_typ,
           main.financial_division_id,
           main.financial_division_name,
           main.financial_sub_division_id,
           main.financial_sub_division_name,
           main.hs_area_id,
           main.hs_area_name,
           main.som_hs_area_id,
           main.som_hs_area_name,
           main.som_group_id,
           main.som_group_name,
           main.som_department_id,
           main.som_department_name,
           main.som_division_id,
           main.som_division_name,
           main.ProcedureOrderEpicId,
           main.proc_code,
           main.proc_name,
           main.referral_type,
           main.referral_status,
           main.referral_status_reason,
           main.referral_priority,
           main.EncounterEpicCsn,
           main.encounter_type,
           main.VisitType,
           main.FirstEncounterInstant,
           main.CreationToFirstEncounterDate,
           main.PAT_ID,
           main.GeneratedByOrder_YesNo,
           main.AppointmentSerialNumber,
           main.AppointmentInstant,
           main.AppointmentStatus,
           main.RescheduledVisitKey,
           main.CancellationInstant,
           main.ReasonAppointmentCanceled,
           main.CancellationInitiator,
		   main.CreationToFirstApptDate_WithCanceled

    FROM [CDW_App].[Rptg].[vwDim_Date] dt

        LEFT OUTER JOIN
        ( -- Main

            SELECT DISTINCT
                   -- Required columns for Tab Table.

                   -- Patient
                   CAST(pat.BirthDate AS DATETIME) AS [person_birth_date],
                   CAST(pat.Sex AS VARCHAR(255)) AS [person_gender],
				   CAST(pat.PatientEpicId AS VARCHAR(18)) AS [PAT_ID],
                   TRY_CAST(pat.PrimaryMrn AS INT) AS [person_id],
                   CAST(pat.Name AS VARCHAR(200)) AS [person_name],

                   -- Patient's age as of Consult Visit date.
                   CASE
                       WHEN age.Years < 18 THEN
                           CAST(1 AS INT)
                       ELSE
                           CAST(0 AS INT)
                   END AS [peds],

                   -- Epic Department associated with the Consult Visit.
                   mdm.EPIC_DEPARTMENT_ID AS [epic_department_id],
                   mdm.EPIC_DEPT_NAME AS [epic_department_name],
                   mdm.EPIC_EXT_NAME AS [epic_department_name_external],

                   -- Provider associated with the Consult Visit.
                   TRY_CAST(prov.ProviderEpicId AS INT) AS [provider_id],
                   CAST(COALESCE(prov.Name, '*Unspecified') AS VARCHAR(50)) AS [provider_name],
                   CAST(prov.Type AS VARCHAR(66)) AS [prov_typ],

                   -- Grouping columns.

                   -- Financial Division
                   -- Based on Provider.
                   TRY_CAST(fin.Financial_Division AS INT) AS [financial_division_id],
                   CAST(fin.Financial_Division_Name AS VARCHAR(150)) AS [financial_division_name],
                   TRY_CAST(fin.Financial_SubDivision AS INT) AS [financial_sub_division_id],
                   CAST(fin.Financial_SubDivision_Name AS VARCHAR(150)) AS [financial_sub_division_name],

                   -- Hospital Area
                   -- Based on Epic Department.
                   CAST(mdm.HS_AREA_ID AS INT) AS [hs_area_id],
                   mdm.HS_AREA_NAME AS [hs_area_name],

                   -- School of Medicine (SOM)
                   -- Based on Provider.
                   som.som_hs_area_id,
                   som.som_hs_area_name,
                   som.som_group_id,
                   som.som_group_name,
                   som.Department_ID AS [som_department_id],
                   CAST(som.Department AS VARCHAR(150)) AS [som_department_name],
                   TRY_CAST(som.Org_Number AS INT) AS [som_division_id],
                   CAST(som.Organization AS VARCHAR(150)) AS [som_division_name],

                   -- Metric specific columns.		
                   ref.ReferralEpicId,		-- event_id
                   ref.ProcedureOrderEpicId,
                   ref.proc_code,
                   ref.proc_name,
                   ref.referral_type,
                   ref.Class,				-- event_category
                   ref.referral_status,
                   ref.referral_status_reason,
                   ref.referral_priority,
                   ref.EncounterEpicCsn,
                   ref.encounter_type,
                   ref.VisitType,
                   ref.CreationInstant,		-- event_date
                   ref.FirstEncounterInstant,
                   ref.CreationToFirstEncounterDate,
				   ref.GeneratedByOrder_YesNo,
				   ref.AppointmentSerialNumber,
				   ref.AppointmentInstant,
				   ref.AppointmentStatus,
				   ref.RescheduledVisitKey,
				   ref.CancellationInstant,
				   ref.ReasonAppointmentCanceled,
				   ref.CancellationInitiator,

				   -- Number of business days (weekdays excluding holidays) between the Referral Creation Date (event_date column)
				   -- and the earliest date between the First Scheduled Appointment Date (AppointmentInstant column)
				   -- and the First Scheduled, Non-Canceled Appointment Date (FirstEncounterInstant column).
				   (SELECT COUNT(*)
					FROM [CDW].[FullAccess].[DateDim] bus
					WHERE 1 = 1
						  AND bus.Weekend = 0
						  AND bus.IsHoliday = 0
						  AND bus.DateValue >= CAST(ref.CreationInstant AS DATE)
						  AND bus.DateValue < CASE
												 WHEN ref.AppointmentInstant > ref.FirstEncounterInstant THEN
													 CAST(ref.FirstEncounterInstant AS DATE)
												 ELSE
													 CAST(ref.AppointmentInstant AS DATE)
											 END) AS [CreationToFirstApptDate_WithCanceled]

            FROM #ref ref

                INNER JOIN [CDW].[FullAccess].[PatientDim] pat
                    ON ref.PatientDurableKey = pat.DurableKey
                       AND pat.IsCurrent = 1
                       AND pat.IsValid = 1
                       AND pat.IsHistoricalPatient = 0
                       AND pat.Test = 0
                       AND pat.DurableKey <> 15282261 /* ANONYMOUS HIM ONLY,REG IN ERROR TESTPATIENTS MRN 4233223 */

                INNER JOIN [CDW].[FullAccess].[DurationDim] age
                    ON ref.AgeKey = age.DurationKey

                INNER JOIN [CDW].[FullAccess].[DepartmentDim] dep
                    ON ref.DepartmentKey = dep.DepartmentKey

                INNER JOIN [CDW].[FullAccess].[ProviderDim] prov
                    ON ref.PrimaryVisitProviderDurableKey = prov.DurableKey
                       AND prov.IsCurrent = 1

                LEFT OUTER JOIN #mdm mdm
                    ON TRY_CAST(dep.DepartmentEpicId AS NUMERIC(18, 0)) = mdm.EPIC_DEPARTMENT_ID

                LEFT OUTER JOIN [CDW_App].[Rptg].[vwDim_Clrt_SERsrc] fin
                    ON prov.ProviderEpicId = fin.PROV_ID

                LEFT OUTER JOIN [CDW_App].[Rptg].[vwRef_OracleOrg_to_EpicFinancialSubdiv] som
                    ON fin.Financial_SubDivision = som.Epic_Financial_Subdivision_Code

        ) main
            ON CAST(main.CreationInstant AS DATE) = CAST(dt.day_date AS DATE)

    WHERE 1 = 1

          AND COALESCE(main.hs_area_id, 1) = 1 -- Medical Center

          AND dt.day_date >= @locStartDate
          AND dt.day_date < @locEndDate;
*/
END;

GO