USE CLARITY

SELECT HL_REQ_INFO.HLR_ID NUMERICBASEID,
       HL_REQ_INFO.REQ_START_PLF_ID STARTLOCATIONID,
       HL_REQ_INFO.REQ_END_PLF_ID ENDLOCATIONID,
       CAST( HL_REQ_INFO.REQ_SERV_AREA_ID AS varchar(50) ) SERVICEAREAID,
       CASE WHEN HL_REQ_INFO.REQ_PRIORITY_C IS NULL THEN '*Unspecified'
            WHEN ZC_HL_REQ_PRIORITY.HL_REQ_PRIORITY_C IS NULL THEN '*Unknown'
            ELSE ZC_HL_REQ_PRIORITY.NAME END REQUESTPRIORITY,
       CASE WHEN HL_REQ_INFO.REQ_MODE_C IS NULL THEN '*Unspecified'
            WHEN ZC_HL_REQ_MODE.HL_REQ_MODE_C IS NULL THEN '*Unknown'
            ELSE ZC_HL_REQ_MODE.NAME END REQUESTMODE,
       CASE WHEN HL_REQ_INFO.REQ_STATUS_C IS NULL THEN '*Unspecified'
            WHEN ZC_HL_REQ_STATUS.HL_REQ_STATUS_C IS NULL THEN '*Unknown'
            ELSE ZC_HL_REQ_STATUS.NAME END REQUESTSTATUS,
       CASE WHEN HL_REQ_INFO.REQ_STATUS_C <> 40 THEN NULL
            WHEN HL_REQ_INFO.REQ_CANCEL_RSN_C IS NULL THEN '*Unspecified'
            WHEN ZC_HL_REQ_CANCEL_RSN.HL_REQ_CANCEL_RSN_C IS NULL THEN '*Unknown'
            ELSE ZC_HL_REQ_CANCEL_RSN.NAME END CANCELREASON,
       CASE WHEN HL_REQ_INFO.PRIMARY_LINKED_EVENT_C IS NULL THEN '*Unspecified'
            WHEN ZC_HL_REQ_LINKED_EVENT.HL_REQ_LINKED_EVENT_C IS NULL THEN '*Unknown'
            ELSE ZC_HL_REQ_LINKED_EVENT.NAME END PRIMARYLINKEDEVENTTYPE,
       HL_REQ_INFO.REQ_PAT_ID PATIENTID,
       HL_REQ_INFO.REQ_ADMISSION_PAT_ENC_CSN_ID ADMISSIONCSN,
       HL_REQ_INFO.REQ_PEND_ID BEDREQUESTID,
       CASE WHEN HL_REQ_INFO.REQ_REGION_SEC_ID IS NULL THEN '*Unspecified'
            WHEN RequestRegion.RECORD_ID IS NULL THEN '*Unknown'
            ELSE RequestRegion.RECORD_NAME END REGION,
       HL_REQ_INFO.REQ_REGION_SEC_ID REGIONID,
       HL_REQ_INFO.REQ_CANCEL_USER_ID CANCELUSERID,
       CAST( HL_REQ_INFO.REQ_CREATE_DEPARTMENT_ID AS varchar(50) ) CREATIONDEPARTMENTID,
       CASE WHEN HL_REQ_INFO.REQ_TEMPLATE_TASK_ID IS NULL THEN '*Unspecified'
            WHEN TASK_TEMPLATES.TASK_ID IS NULL THEN '*Unknown'
            WHEN TASK_TEMPLATES.TASK_NAME IS NULL THEN '*Unknown'
            ELSE TASK_TEMPLATES.TASK_NAME END TASK,
       CASE WHEN HL_REQ_INFO.REQ_TASK_SUBTYPE_C IS NULL THEN '*Unspecified'
            WHEN ZC_HL_TASK_SUBTYPE.HL_TASK_SUBTYPE_C IS NULL THEN '*Unknown'
            ELSE ZC_HL_TASK_SUBTYPE.NAME END TASKSUBTYPE,
       HL_REQ_INFO.REQ_START_LOCAL_DTTM REQUESTSTARTINSTANT,
       HL_REQ_INFO.REQ_ACTIVATION_LOCAL_DTTM ACTIVATIONINSTANT,
       HL_REQ_INFO.REQ_INIT_ACTIVATION_LOCAL_DTTM INITIALACTIVATIONINSTANT,
       HL_REQ_INFO.REQ_FUNC_COMP_LOCAL_DTTM FUNCTIONALLYCOMPLETEDINSTANT,
       StatusTimestamps.CanceledDttm CANCELEDINSTANT,
       COALESCE( HL_REQ_INFO.REQ_FUNC_COMP_LOCAL_DTTM, StatusTimestamps.CanceledDttm ) RESOLUTIONINSTANT,
       CASE WHEN HL_REQ_INFO.REQ_STATUS_C = 35 THEN 1
            ELSE 0 END ISCOMPLETED,
       CASE WHEN HL_REQ_INFO.REQ_STATUS_C = 40 THEN 1
            ELSE 0 END ISCANCELED,
       CASE WHEN HL_REQ_INFO.REQ_PRIORITY_C = 0 THEN 1
            ELSE 0 END ISSTATPRIORITY,
       CASE WHEN HL_REQ_INFO.REQ_SECTOR_SEC_ID IS NULL THEN '*Unspecified'
            WHEN RequestSector.RECORD_ID IS NULL THEN '*Unknown'
            WHEN RequestSector.HL_GENERAL_SECTOR_DISPLAY_NAME IS NOT NULL THEN RequestSector.HL_GENERAL_SECTOR_DISPLAY_NAME
            ELSE RequestSector.RECORD_NAME END SECTOR,
       HL_REQ_INFO.REQ_SECTOR_SEC_ID SECTOREPICID
  FROM HL_REQ_INFO
    LEFT OUTER JOIN ( SELECT HL_REQ_STATUS_AUDIT.HLR_ID,
                             MAX( CASE WHEN HL_REQ_STATUS_AUDIT.STATUS_C = 40 THEN HL_REQ_STATUS_AUDIT.EVENT_LOCAL_DTTM ELSE NULL END ) CanceledDttm
                        FROM HL_REQ_STATUS_AUDIT
                        WHERE HL_REQ_STATUS_AUDIT.HLR_ID > <<LowerBound>>
                          AND HL_REQ_STATUS_AUDIT.HLR_ID <= <<UpperBound>>
                        GROUP BY HL_REQ_STATUS_AUDIT.HLR_ID ) StatusTimestamps
      ON HL_REQ_INFO.HLR_ID = StatusTimestamps.HLR_ID
    LEFT OUTER JOIN TASK_TEMPLATES
      ON HL_REQ_INFO.REQ_TEMPLATE_TASK_ID = TASK_TEMPLATES.TASK_ID
    LEFT OUTER JOIN CL_SEC RequestRegion
      ON HL_REQ_INFO.REQ_REGION_SEC_ID = RequestRegion.RECORD_ID	  
    LEFT OUTER JOIN CL_SEC RequestSector
      ON HL_REQ_INFO.REQ_SECTOR_SEC_ID = RequestSector.RECORD_ID
    LEFT OUTER JOIN ZC_HL_TASK_SUBTYPE
      ON HL_REQ_INFO.REQ_TASK_SUBTYPE_C = ZC_HL_TASK_SUBTYPE.HL_TASK_SUBTYPE_C
    LEFT OUTER JOIN ZC_HL_REQ_PRIORITY
      ON HL_REQ_INFO.REQ_PRIORITY_C = ZC_HL_REQ_PRIORITY.HL_REQ_PRIORITY_C
    LEFT OUTER JOIN ZC_HL_REQ_MODE
      ON HL_REQ_INFO.REQ_MODE_C = ZC_HL_REQ_MODE.HL_REQ_MODE_C
    LEFT OUTER JOIN ZC_HL_REQ_STATUS
      ON HL_REQ_INFO.REQ_STATUS_C = ZC_HL_REQ_STATUS.HL_REQ_STATUS_C
    LEFT OUTER JOIN ZC_HL_REQ_CANCEL_RSN
      ON HL_REQ_INFO.REQ_CANCEL_RSN_C = ZC_HL_REQ_CANCEL_RSN.HL_REQ_CANCEL_RSN_C
    LEFT OUTER JOIN ZC_HL_REQ_LINKED_EVENT
      ON HL_REQ_INFO.PRIMARY_LINKED_EVENT_C = ZC_HL_REQ_LINKED_EVENT.HL_REQ_LINKED_EVENT_C
  WHERE HL_REQ_INFO.REQ_STATUS_C IN ( 35, 40 )
    AND HL_REQ_INFO.HLR_TYPE_C = 1
    AND HL_REQ_INFO.HL_FUNC_TYPE_C = 10
    AND HL_REQ_INFO.HLR_ID > <<LowerBound>>
    AND HL_REQ_INFO.HLR_ID <= <<UpperBound>>