USE DS_HSDM_App

SELECT [sk_Dash_Telemedicine_Encounters_Tiles]
      ,[event_type]
      ,[event_count]
      ,[event_date]
      ,[event_id]
      ,[event_category]
      ,tmed.[epic_department_id]
      ,tmed.[epic_department_name]
      ,[epic_department_name_external]
      ,tmed.[fmonth_num]
      ,tmed.[fyear_num]
      ,tmed.[fyear_name]
	  ,dd.year_num
      ,[report_period]
      ,[report_date]
      ,[peds]
      ,[transplant]
      ,[oncology]
      ,tmed.[sk_Dim_Pt]
      ,tmed.[sk_Fact_Pt_Acct]
      ,tmed.[sk_Fact_Pt_Enc_Clrt]
      ,[person_birth_date]
      ,[person_gender]
      ,[person_id]
      ,[person_name]
      ,[practice_group_id]
      ,[practice_group_name]
      ,[provider_id]
      ,[provider_name]
      ,[sk_dim_physcn]
      ,[service_line_id]
      ,[service_line]
      ,[sub_service_line_id]
      ,[sub_service_line]
      ,[opnl_service_id]
      ,[opnl_service_name]
      ,[corp_service_line_id]
      ,[corp_service_line_name]
      ,[hs_area_id]
      ,[hs_area_name]
      ,[financial_division_id]
      ,[financial_division_name]
      ,[financial_sub_division_id]
      ,[financial_sub_division_name]
      ,[rev_location_id]
      ,[rev_location]
      ,[som_group_id]
      ,[som_group_name]
      ,[som_department_id]
      ,[som_department_name]
      ,[som_division_id]
      ,[som_division_name]
      ,[w_department_id]
      ,[w_department_name]
      ,[w_department_name_external]
      ,[w_practice_group_id]
      ,[w_practice_group_name]
      ,[w_service_line_id]
      ,[w_service_line_name]
      ,[w_sub_service_line_id]
      ,[w_sub_service_line_name]
      ,[w_opnl_service_id]
      ,[w_opnl_service_name]
      ,[w_corp_service_line_id]
      ,[w_corp_service_line_name]
      ,[w_report_period]
      ,[w_report_date]
      ,[w_hs_area_id]
      ,[w_hs_area_name]
      ,[w_financial_division_id]
      ,[w_financial_division_name]
      ,[w_financial_sub_division_id]
      ,[w_financial_sub_division_name]
      ,[w_rev_location_id]
      ,[w_rev_location]
      ,[w_som_group_id]
      ,[w_som_group_name]
      ,[w_som_department_id]
      ,[w_som_department_name]
      ,[w_som_division_id]
      ,[w_som_division_name]
      ,[pod_id]
      ,[pod_name]
      ,[hub_id]
      ,[hub_name]
      ,[w_pod_id]
      ,[w_pod_name]
      ,[w_hub_id]
      ,[w_hub_name]
      ,[w_som_hs_area_id]
      ,[w_som_hs_area_name]
      ,[w_upg_practice_flag]
      ,[w_upg_practice_region_id]
      ,[w_upg_practice_region_name]
      ,[w_upg_practice_id]
      ,[w_upg_practice_name]
      ,[Epic_Department_Specialty]
      ,[Encounter_CSN]
      ,[Encounter_Status_Category]
      ,[Encounter_Status]
	  ,appt.APPT_STATUS_C
	  ,appt.APPT_STATUS_NAME
	  ,appt.APPT_STATUS_FLAG
      ,[Communication_Type]
      ,[Visit_Type]
      ,[Encounter_Type]
      ,[Event_Date_Within_Nightly_Processing]
      ,[Prov_Specialty]
      ,[Prov_Type]
      ,[Prov_Resource_Type]
      ,[Smartphrase_ID]
      ,[Smartphrase_Name]
      ,[HB_HAR]
      ,[PB_HAR]
      ,[MyChart_Status]
      ,[Visit_Coverage]
      ,tmed.[Load_Dtm]
      ,[Appt_Note]
      ,[Smartdata_Element]
      ,[Comm_Type_Billing]
      ,[Pt_Home_Resource]
      ,[Postal_Code]
      ,[County]
      ,[StateorProvince]
      ,[Country]
      ,[Guarantor]
      ,[w_serviceline_division_flag]
      ,[w_serviceline_division_id]
      ,[w_serviceline_division_name]
      ,[w_mc_operation_flag]
      ,[w_mc_operation_id]
      ,[w_mc_operation_name]
      ,[w_post_acute_flag]
      ,[w_ambulatory_operation_flag]
      ,[w_ambulatory_operation_id]
      ,[w_ambulatory_operation_name]
      ,[w_inpatient_adult_flag]
      ,[w_inpatient_adult_id]
      ,[w_inpatient_adult_name]
      ,[w_childrens_flag]
      ,[w_childrens_id]
      ,[w_childrens_name]
      ,tmed.[Telehealth_Mode_C]
      ,tmed.[Telehealth_Mode_Name]
      ,[UVaID]
      ,tmed.[CANCEL_REASON_NAME]
      ,tmed.[APPT_DTTM]
      ,[EMPlye_Nme]
      ,[EMPlye_Systm_Login]
  FROM [DS_HSDM_App].[TabRptg].[Dash_Telemedicine_Encounters_Tiles] tmed
  LEFT OUTER JOIN DS_HSDW_Prod.Rptg.vwDim_Date dd
  ON dd.day_date = CAST(tmed.event_date AS SMALLDATETIME)
  LEFT OUTER JOIN DS_HSDM_App.Stage.Scheduled_Appointment appt
  ON appt.PAT_ENC_CSN_ID = tmed.Encounter_CSN

LEFT OUTER JOIN DS_HSDM_App.Mapping.Epic_Dept_Groupers g
ON g.epic_department_id = tmed.epic_department_id
LEFT OUTER JOIN DS_HSDM_App.Mapping.Ref_Clinical_Area_Map c
ON c.sk_Ref_Clinical_Area_Map = g.sk_Ref_Clinical_Area_Map
LEFT OUTER JOIN DS_HSDM_App.Mapping.Ref_Service_Map s
ON s.sk_Ref_Service_Map = c.sk_Ref_Service_Map
LEFT OUTER JOIN DS_HSDM_App.Mapping.Ref_Organization_Map o
ON o.organization_id = s.organization_id

  WHERE
	dd.year_num = 2022
	AND tmed.StateorProvince = 'Virginia'
	AND tmed.County = 'Albemarle'
	AND tmed.Encounter_Status_Category <> 'Invalid'
	AND g.ambulatory_flag = 1
	--ORDER BY tmed.Telehealth_Mode_Name
	ORDER BY appt.APPT_STATUS_C